### ISSUE TITLE
greenworks.initAPI() return false

### ISSUE THREAD

**Issue by armaldio** [greenheartgames/greenworks#101]
Hello, 

I can't get greenworks to work.

Windows 10 x64
Node.js 6.5.0, Chromium 53.0.2785.113, and Electron 1.4.0.

What I've done : 

* Clone electron quick start
* download prebuild greenworks for electron 1.4.0 x64
* So here is my architecture : 

![capture](https://cloud.githubusercontent.com/assets/3089715/20031990/61ab3c5e-a381-11e6-9458-2b302d8fbb61.PNG)

* Put the content of main.js from sample electron to renderer.js
* npm start

My steam is not running as administrator
(though, I have tried running npm start as administrator)

How can I make it working ?
Thanks

EDIT: Just tried with prebuilt 1.3.3 and electron 1.3.3, same result

**Comment by hokein** [comment]
Can you use `greenworks.init()` API? That API can prompt up friendly error message.

**Comment by armaldio** [comment]
You mean use another function from the API even if the init fail?

**Comment by hokein** [comment]
@armaldio There is two APIs `init` and `initAPI`, both of them have same functionality, but the later provides better error message while the initialization of Steam fails.

I mean you can replace `greenworks.initAPI` with `greenworks.init`, and you can see the error message, which might be tell us what's wrong with your issue (From your report, I can't found the reason directly).

**Comment by armaldio** [comment]
Nice, didn't notice the difference, I will try that. Thanks.

**Comment by armaldio** [comment]
Hey, 

Got this error now : 
```javascript
Uncaught Error: Steam initialization failed, but Steam is running, and steam_appid.txt is present and valid.Maybe that's not really YOUR app ID? 123456
```

**Comment by MadSpyxFR** [comment]
App ID 123456 is an old appID for test; no longer supported when you want to init API

**Comment by armaldio** [comment]
@MadSpyxFR What should I do for test then ?

Readme.md - l 226 : 
```
echo 123456 > steam_appid.txt
```

**Comment by MadSpyxFR** [comment]
Even if 123456 is no longer supported for advanced APi features, SteamAPI_Init() should returns true.
Try to add greenworks-win32.node and steam_api.dll /steam_api.lib in your lib folder.

**Comment by armaldio** [comment]
Instead of `greenworks.initAPI()` or `greenworks.init()` is could be able to use `SteamAPI_Init()` or `greenworks.SteamAPI_Init()` ?

**Comment by MadSpyxFR** [comment]
SteamAPI_Init() is already called by greenworks.initAPI() and greenwokrs.init() (by `if (this.initAPI()) return;` )
greenworks.init() check if SteamAPI_Init() returns true and try to detect why init fails (test if steam is running and check steam_appid.txt ...)

**Comment by armaldio** [comment]
So I should be able to use greenworks functions anyway ?

To solve this issue I have to get a valid steam appid ?

**Comment by MadSpyxFR** [comment]
Greenworks functions are not available if SteamAPI_Init() fails.
You can try to set the appID of a game you own on Steam

**Comment by hokein** [comment]
@armaldio 
As @MadSpyxFR mentioned above, `123456` is not a valid steam app ID. `Steamworks` SDK requires a valid steam app ID, which means `greenworks.initAPI()` must return true before you use other greenworks methods.

For test, you can use the steam app id from an example provided by `Steamworks`.

I think we should update the readme to avoid this confusion.

**Comment by armaldio** [comment]
Awesome

I set my app id to 480
but that wasn't working

Then i changed back greenworks.init to greenworks.initAPI and it works
Thanks to you two @hokein @MadSpyxFR <3
