### ISSUE TITLE
Confusion about Require.

### ISSUE THREAD

**Issue by michaelpelletier** [greenheartgames/greenworks#102]
Hi there.

I have an app for release on Steam that's built using Electron and I've recently begun implementing Greenworks for Achievement support (which has been awesome so far), but I'm having an issue that I'm not sure is an actual issue or just something that I'm doing wrong. 

Everything works peachy locally, but when I'm packaging the app with Electron (with Asar turned on), the `require` for Greenworks seems to fail.

I've tried having it as `require('./greenworks')` and `require('../greenworks')` and `require('greenworks')` and it doesn't seem to find it in any case. I can't discern if it's a) because of asar, b) because greenworks isn't installed _through_ npm in the way that other things are, or c) because I've installed something incorrectly.

Would love love love to hear any suggestions on this.

**Comment by MadSpyxFR** [comment]
if you use `require('./greenworks')`, greenworks.js have to be on the same folder than your index.thml/main js and node files in [currentdir]\lib\

**Comment by michaelpelletier** [comment]
Yeah that's how I had it.

```
app/
  app.js
  greenworks.js
  index.html
  lib/ (containing both the node file and required dlls)
  main.js
  node_modules/ (containing other required files like electron files)
```

And again, that works great locally, but after I compile everything into an application via electron packager, it seems to no longer be able to find the file.

**Comment by hokein** [comment]
@michaelpelletier 
Do you use `electron-packager` to package your app? Can you paste the error message? Does the error message say "`.node` not found“?

**Comment by michaelpelletier** [comment]
@hokein 
I do indeed use `electron-packager`. I don't think it even gets to the `.node` file yet. 
My console gives me this:

```
Uncaught Error: Cannot find module 'greenworks'
Uncaught ReferenceError: greenworks is not defined
```

**Comment by hokein** [comment]
hmm, I don't think this issue is a greenworks relevant issue, and I'm not an expert on `electron-packager`, so I'd suggest you ask this question there.

**Comment by MadSpyxFR** [comment]
@michaelpelletier  check [https://github.com/electron-userland/electron-packager/issues/217](url) and/or [https://discuss.atom.io/t/cant-use-app-module-in-render-process/17326](url)

**Comment by michaelpelletier** [comment]
I'll check those out, @MadSpyxFR - it definitely looks like there's something there. Thanks, all!
