### ISSUE TITLE
Get user avatar?

### ISSUE THREAD

**Issue by PierrePaul** [greenheartgames/greenworks#103]
I've been reading the docs again and again, but I haven't found a way to get the user avatar.
I tried using the `getLargeFriendAvatar` and passing the current user steam_id without success.

Am I missing something obvious or I am just doing it wrong with `getLargeFriendAvatar` ?

**Comment by MadSpyxFR** [comment]
Which value returns  `getLargeFriendAvatar` ?

**Comment by PierrePaul** [comment]
-1, but I'm not listening on any events. Any ideas what I should I should listen to? Since I'm not loading any friends...

**Comment by MadSpyxFR** [comment]
-1 means the image is not loaded yet, you have to listen the event `'avatar-image-loaded'` (returns CSteamID of user, image handle and image size,) then use greenworks.getImageRGBA(handle)
See [https://github.com/greenheartgames/greenworks/blob/master/docs/setting.md](url) for more info (bottom of the page)
Note: `getLargeFriendAvatar` works for friend and current user

**Comment by hokein** [comment]
@PierrePaul 
@MadSpyxFR has pointed out the reason. You are required to listen `avatar-image-loaded` event for  `getLargeFriendAvatar` API.
