### ISSUE TITLE
Disable notifications?

### ISSUE THREAD

**Issue by michaelpelletier** [greenheartgames/greenworks#109]
Hi all,

Another question / comment / possible issue from me. Something I've noticed working with Electron (1.4.3) is that it / Chromium doesn't have "consistent" support for the Steam Overlay. That's fine.

In order to support still having Achievements display when unlocked, what I did instead was write something custom inside my application to display a custom achievement popup (and also send the message via Greenworks to Steam to actually unlock that achievement).

This works marvelously as it is, but the problem is that there are some instances in which the Steam achievement unlocked popup actually does trigger. Eg, it doesn't work on my Mac but it works on my Windows machine. And I don't know if it's even consistent between Operating Systems to be able to "disable" mine for circumstances in which it will work.

So, my question is two-parts.
1. Does anyone know when Achievement popups do/don't work?
2. Is it possible to fire something via Greenworks to disable the Steam popups and be able to safely rely on my own?

**Comment by MadSpyxFR** [comment]
Hi,
1. (theory) Achievement popup are displayed by steam overlay (via GameOverlayUI.exe process and D3D) once the achievement is unlocked and stat are stored only. 
Note: the overlay works only if you have a constant framerate so you need to refresh the canvas (black bars from letterbox scale (when you enter in fullscreen with a canvas/windows size different than 16:9 res) or fixed background image could broke the overlay and popups). 
Note2: Overlay seems to wor better on Mac with nw.js than electron.
2. I don't see in steamworks any docs about this features. The only way seems to disable overlay.

**Comment by hokein** [comment]
@MadSpyxFR has answered most questions, thanks!

Steam overlay is automatically hooked in your game be default. There is no way in Steamworks can disable it. You may ask Valve to disable it for you. But for electron/nw.js-based games, overlay doesn't work perfectly, you have to pass `in-progress-gpu` command-line flag to enable it (it still fails in some cases, #16), so there is a hack way to disable overlay: don't pass `in-progress-gpu` command-line flag to your application.

To disable achievement popup, you have to disable overlay.

**Comment by michaelpelletier** [comment]
@hokein Is `in-progress-gpu` passed by default? I didn't do anything special to pass it specifically.
