### ISSUE TITLE
Cannot ship linux32 and linux64

### ISSUE THREAD

**Issue by TatriX** [greenheartgames/greenworks#110]
Linux dlls for x32 and x64 are using the same name.
The only simple way I've found to ship both versions is changing `greenworks.js` as follows:
```js
...
 greenworks = require('./lib/linux64/greenworks-linux64')
...
 greenworks = require('./lib/linux32/greenworks-linux32')
```
That way I can place different libsteam_api.so in this folders.
If there is a proper way of doing this?

**Comment by hokein** [comment]
I can not figure out a more elegant way to ship your game with both 32bit and 64bits steam linux dlls at once. The way you mentioned seems fine to me although it requires some modifications in `greenworks.js`.

**Comment by TatriX** [comment]
Should I send a PR or you don't interested in this change?

**Comment by MadSpyxFR** [comment]
you could create 2 depots/build in your steamworks (one for each linux version)
