### ISSUE TITLE
getEncryptedAppTicket return error

### ISSUE THREAD

**Issue by easy63** [greenheartgames/greenworks#111]
Hi, I'm trying to add authorization checks in your game and use this library. Use nw.js 18.2 (higher version does not work with the library).

`

	let wlog = function(_message) {
		document.body.innerHTML = _message + '<br />' + document.body.innerHTML;
	};

	let greenworks = require('./steam/greenworks');

	if(!greenworks.initAPI())
		return wlog('Steam init API error.');

	if(!greenworks.isSteamRunning())
		return wlog('Steam is not running.');

	greenworks.getEncryptedAppTicket('something', function(_ticket) {
		wlog('ticket: ' + _ticket);
	}, function(err) {
		wlog(err);
	});

`

I run my app from steam and it says that it is running. initAPI and isSteamRunning work fine but getEncryptedAppTicket always returns "Error on getting encrypted app ticket.".

And I don't know why, but getAppId method does not exist.

I threw all of the appropriate libraries (two) into the folder as stated in the documentation

Why is this happening? What did I do wrong? Help please :)

ps. debian testing x64. nw.js.

**Comment by hokein** [comment]
I tested the API with an APPID of the example `Spacewar` provided in Steam SDK, and it works as expected.

Have you set up your Steam authentication  settings of your game? From [Steamworks doc](https://partner.steamgames.com/documentation/auth):

> Before using Encrypted Application Tickets, you must generate a private key for each title. You can do this by navigating to Edit Steamworks Settings for your application and selecting 'SDK Auth' from the 'Security' drop-down. This key will be associated with your title's AppID and any downloadable content for that title. The keys must be stored securely, and must not be distributed with a game client.

I agree that the error message "Error on getting encrypted app ticket" doesn't provide much value to help developers diagnose problems. I think we can expose more details e.g. return code in our error callbacks.

**Comment by easy63** [comment]
I only created the key, but do not understand how to use it. The documentation does not say anything about it or I just don't see :(

**Comment by hokein** [comment]
I would suggest you to seek help from Steamworks community as we could do nothing from greenworks side.

**Comment by easy63** [comment]
I pressed "publish", restarted Steam and it working! Thanks! :)
