### ISSUE TITLE
It's not working again

### ISSUE THREAD

**Issue by easy63** [greenheartgames/greenworks#112]
I get a ticket, but greenworks.EncryptedAppTicketSymmetricKeyLength equal to undefined.

And I don't understand the string var key = new Buffer(32); it's just filled with zeros. Why? What should I do with this?

Why is this not described in detail in the documentation?

**Comment by easy63** [comment]
My key in the "auth sdk" is not 32 characters.

**Comment by hokein** [comment]
The sample code in [`authentication.md`](https://github.com/greenheartgames/greenworks/blob/master/docs/authentication.md) is not completed. You have to specify the your key like ` var buffer = new Buffer([0x0a, ..., 0x0b]);`.

The document might be not clear enough, I will clarify it.
