### ISSUE TITLE
Update for a latest nw.js

### ISSUE THREAD

**Issue by TatriX** [greenheartgames/greenworks#113]
Are you planning to release an updated version soon?
Thank you.

**Comment by hokein** [comment]
Previously I was waiting for chrome 54 upgrade in electron before releasing Greenworks 0.8.0, but the upgrade process was quite hard, and is not completed yet. I think it is fine to create a new release only for nw.js v0.18 at the moment.

**Comment by TatriX** [comment]
The latest nwjs version is 19.4 though.

**Comment by hokein** [comment]
The latest version (nw.js v0.18.8 & v0.19.4) has been released now. The release binaries can be found at https://github.com/greenheartgames/greenworks/releases.

**Comment by Zamiell** [comment]
Hello hokein. Is there a rough ETA on a v0.8.0 release for Electron? Alternatively, are there any similar libraries that offer "getAuthSessionTicket" functionality?

**Comment by hokein** [comment]
@Zamiell not yet. The chrome54 upgrade of electron is still not completed yet (It would be happened this month probably). I will publish a v0.8.0 release for electron after electron gets upgrade to chrome54.
