### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by rezoner** [greenheartgames/greenworks#12]
Any plans to support leaderboards?

**Comment by Baccanno** [comment]
Well there will always be a hacking possibility, however it might be interesting to have this still IMHO. Leaderboards can be terribly addictive to players even if they are hackable (see super hexagon)

**Comment by MarxGames** [comment]
Maybe only support the Retrieving Leaderboard data parts then? Leave submitting for the server side.

**Comment by Baccanno** [comment]
Well I did it with server only for the Leaderboard part, I didn't really
get what you said at first, but then noticed there was an REST API for
leaderboards and so :) Indeed it's not that interesting as you said

2015-06-07 11:07 GMT+02:00 Margus Ojanurme <notifications@github.com>:

> Maybe only support the Retrieving Leaderboard data parts then? Leave
> submitting for the server side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenheartgames/greenworks/issues/12#issuecomment-109724007>
> .
>



-- 
Michaël Picovschi, Morphiks
http://www.morphiks.com

**Comment by MarxGames** [comment]
I take back my request. Not required at the moment, since leaderboards are fundamentally flawed and Steam completely ignores their own documentation.

Taken from their documentation:
Writes - If this is set to Trusted, the leaderboard scores cannot be set by clients, and can only be set by via SetLeaderboardScore WebAPI. Defaults to false.

Does not matter if you set writes to trusted, everyone can still publish fake scores.

**Comment by artch** [comment]
What is the status here? Are there any issues with Steam trusted writes yet? And any plans to implement it in greenworks? I'm interested in integrating leaderboards into my greenworks-based game.

**Comment by agar3s** [comment]
Hi! I was checking another way to upload data to the leaderboard from steam, but there is no webApi available for that, and I'm not sure how to update this library to support that.
How do you suggest to submit scores to leaderboard?

**Comment by hokein** [comment]
@agar3s 
Greenworks doesn't provide APIs to manage leaderboard, although Steam SDK does provide them.

You could find web APIs of leaderboard at https://lab.xpaw.me/steam_api_documentation.html#ISteamLeaderboards.
