### ISSUE TITLE
DLC?

### ISSUE THREAD

**Issue by michaelpelletier** [greenheartgames/greenworks#121]
Hey are there methods / plans for methods that can discern whether a user owns DLC for the app they're using?

**Comment by hokein** [comment]
If steamworks SDK provides such APIs, it makes sense to implement these APIs. 

Could you please specify which APIs in steamworks that you need?

**Comment by michaelpelletier** [comment]
So based on information here - [in the SteamDocs](https://partner.steamgames.com/documentation/dlc#ownership) and [the sdk source](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/steam/isteamapps.h) - it looks like there is a function called `BIsDlcInstalled` that takes in the AppID of the DLC as a parameter.

**Comment by michaelpelletier** [comment]
Also, it looks like there's a callback for checking if someone has bought DLC since starting the game, but since the Steam overlay doesn't work with Electron as it is, I'm less concerned about that.

**Comment by michaelpelletier** [comment]
@hokein Thanks so much for the quick response on this!
