### ISSUE TITLE
Building multiple OS's

### ISSUE THREAD

**Issue by michaelpelletier** [greenheartgames/greenworks#125]
Hey, quick question maybe. 

I'm following the directions for building Greenworks (since the 0.8 release doesn't have Electron binaries) and my mac doesn't seem to build them for linux or windows. Is that expected? I didn't see anything in the troubleshooting or docs specifically about building for multiple OS's.

**Comment by hokein** [comment]
>  my mac doesn't seem to build them for linux or windows

You can't build Linux and Windows binary on your Mac OS X directly. One option is to install Windows/Linux with VirtualMachine like VirtualBox.

**Comment by michaelpelletier** [comment]
Wow, that sucks. :-/ Any chance you have an ETA on the new builds? I've only got enough variant machines to do half of them...

**Comment by hokein** [comment]
@michaelpelletier electron v1.6.1 is promoted from beta to stable yesterday. I have made a new v0.9.0 Greenworks release for nw.js v0.20.3 and electron v1.6.1.
