### ISSUE TITLE
Add support for submitting workshop items for a different app.

### ISSUE THREAD

**Issue by Misto423** [greenheartgames/greenworks#126]
Currently when submitting workshop items, greenworks gets the app id from steam apis and publishes for the same app id.  This is fine for when the app submitting the item is the game itself.  

However, we have a separate application built with greenworks and electron that is a tool in the Steam library.  This gives it a separate app id compared to the game.  There is steam support for this by letting devs specify other app ids that can publish content for your game.  Now when we try to publish an item it tries to publish with the tool id that it gets from steam.

I noticed that the workshop calls are just getting the id from the steam api which fails in this case.  I believe allowing devs to specify a "publish id" that is separate from the running app id would let greenworks support cases for tool development.

**Comment by MadSpyxFR** [comment]
It could be added but the major issue would to add this without breaking existing projects.
I will post a PR tomorrow except if Hokein wants to create one (or sends it) before.

**Comment by Misto423** [comment]
Awesome.  I tried to update it myself, but had problems getting my app to recognize the .node files after building so chances are I broke something.  Then I figured this might be beneficial to others hence the issue.  I appreciate the quick response.  Might save me some time this weekend haha.

**Comment by hokein** [comment]
@MadSpyxFR Thanks for your quick response. Patches are always welcome. Feel free to do that.

**Comment by Misto423** [comment]
Great!  I should be able to do some testing of it next week

**Comment by hokein** [comment]
Fixed in #194.
