### ISSUE TITLE
A Few Readme Suggestions (mostly for Windows Envs)

### ISSUE THREAD

**Issue by Cleod9** [greenheartgames/greenworks#128]
Hi folks, so it took me an unmentionable amount of time to get this to compile and run in 64-bit Windows 7. Figured I would post some suggestions for the readme that may be useful for others :)

**1) Add `steam_api64.dll` to this section.**
```
Copy steam_api.dll/libsteam_api.dylib/libsteam_api.so (from <steam_sdk_path>/redistributable_bin/) to <app-dir>/lib/.
```
If the user doesn't add the 64 bit DLL and is running under 64-bit Windows the user will be presented with a "cannot find module" error at runtime (which is not very informative)

**2) Be more explicit about the difference (or similarities) in file layout of greenworks dependencies between NW/Electron**

In a few places scattered throughout the docs, a `<greenworks_path>` is mentioned but it is not entirely clear if this is referring to the project's copy of `greenworks.js` or the one in the `node_modules/` folder. After much trial-and-error I was able to run this without a node_modules directory at all since i bundled all of my .js into one file, built the greenworks native module myself, and finally deduced i could copy `greenworks.js` into my app's build root.

To alleviate potential confusion with this it may be useful to present readers with a distinction between a `node_modules/`-based greenworks setup VS one that simply uses the prebuilt binaries and `greenworks.js` file. Right now in the readme are implications that there are at least 2 possible organizational patterns here- one that has the lib folder at the app root as described in the NW.js section, and one that has everything under `node_modules` as described in the electron-quick-start section.

**3) Some users running into issues with `node-gyp` might have some luck installing Visual C++ 2015 Build Tools.**

I was actually not able to get `node-gyp` to compile this project at all until I had installed this (which was unfortunate since it forced me to uninstall VS 2015 before I could install Build Tools)

http://landinghub.visualstudio.com/visual-cpp-build-tools

**4) Be more explicit here about the limitation of only being able to compile the OS for your dev environment:**

```
After building finished, you can find the greenworks-(linux/win/osx).node binaries in build/Release.
```
Since electron is generally a cross-platform runtime it may alleviate some confusion to those using tools that generate multi-platform outputs. The readme should state that only the binaries for your environment platform will be built.

**5) Provide more context behind the unusual NPM installation method**

Most Node.js devs are probably not going to quickly pick up on the necessity behind the installation requiring a Git URL + `--ignore-scripts`. It would be extremely informative to provide some context on why the setup requirements work this way. It may also be useful to place a tag of the latest version in the Readme's example git urls (e.g. `#0.9.0`) and be very explicit about using a git url for installation (especially so that people don't get this repo mixed up with the outdated fork on NPM)

-------------------

Hopefully these could be useful to someone running into problems similar to mine

**Comment by hokein** [comment]
@Cleod9 Thanks very much for your detailed feedback and input. These sounds good to me. 
Would you mind sending a PR to improve the document?

I always hope we could provide a clear `readme` document for beginners to make their ramping up process more smooth. As a node developer, it is hard to write instructions covering all stuff from beginners' perspective. I'm open to hear users' feedback and continuously improve the document.
Patch are always welcome :)

**Comment by Cleod9** [comment]
Thanks @hokein , when I have some spare time I can submit some PRs to address each of these. It may be a couple weeks though since I have a tight schedule coming up.

**Comment by hokein** [comment]
@Cleod9  I have done some improvement on the documentation today. I hope it would make the document clearer.

I'm closing this issue now. I believe there is still room to polish the doc, patches are always welcome :)
