### ISSUE TITLE
Prebuild Binaries for electron 1.6.7?

### ISSUE THREAD

**Issue by Bizarrus** [greenheartgames/greenworks#136]
Anyone have prebuilds for `electron 1.6.7`?

**Comment by hokein** [comment]
Ideally, you could use the electron v1.6.1 prebuilt greenworks binaries in electron v1.6.7.

Electron bumps the minor version for each chrome stable release, so the greenworks binary built for a specific electron version should be API compatible for all versions within the same minor version (e.g. greenworks built for electron v1.6.1 works for all v1.6.X). 

It makes sense to update the greenworks release document (like "Greenworks release for electron 1.6.X"), but I need to check whether nw.js follows the same releasing strategy first.
