### ISSUE TITLE
ugcGetItems returns empty array

### ISSUE THREAD

**Issue by Bizarrus** [greenheartgames/greenworks#137]
I tried to get the Steam-Workshop files (AppID [322330](https://steamcommunity.com/workshop/browse/?appid=322330)), but the result is an empty array.

Here is a small example:

    var greenworks = require('../Classes/Greenworks');
    if(greenworks.initAPI()) {
        greenworks.ugcGetItems(greenworks.UGCMatchingType.Items, greenworks.UGCQueryType.RankedByVote, function onSuccess(items) {
            console.log('onSuccess', items);
        }, function onError(error) {
            console.log('onError', error);
        });
    }

**Returns following output**
> onSuccess []

**Comment by hokein** [comment]
I can reproduce it. Need to investigate further.
