### ISSUE TITLE
Get session ticket

### ISSUE THREAD

**Issue by DVassilev** [greenheartgames/greenworks#139]
Hi, is it possible to run this without having steam open and instead run it using nodejs and have it use credentials for a steam account to then get the session ticket? Thanks

**Comment by patrickklug** [comment]
I doubt it is. Wouldn't make sense for steam to allow authentication via third party apps on the machine.
Steam's website does act as a OpenID provider though, if you just need to verify a username:

https://steamcommunity.com/dev

**Comment by DVassilev** [comment]
@patrickklug you can use node-steam-user to authenticate and do actions via the API (even getting encrypted ticket) but why not session ticket?
