### ISSUE TITLE
alternative library for saving Steam avatar as png

### ISSUE THREAD

**Issue by handyplayer13** [greenheartgames/greenworks#145]
Hello,

is there a better way of saving the users Steam avatar as png than using Jimp (getImageRGBA() method)?
The reason is that Jimp takes up almost 15 MB of disk space and, more important, is **loading really, really slow** (loading time increases from some milliseconds to 1-2 seconds). Probably because Jimp has many more features that we don't need.

**So, is there a more lightweight library that can do the same as Jimp?**

I googled myself and found some node.js modules but I couldn't get any of them to work. I don't have the background knowledge of this image stuff and there were no concrete examples for this special case. As much as I know is, that we need to convert rgba values in a uint8 array to a png file but I have no idea how to do this.

Can anyone tell me a library/module and also give an example?
I just wanted to get the users Steam avatar and suddenly I have to deal with this complicated situation. Help is really appreciated. =D

Greetings,
Sebastian

**Comment by handyplayer13** [comment]
After some thinking I came to the idea that I could convert the rgba values to a data uri, so I can display the avatar directly. That's how I found the module "rgba-to-datauri" which only needs 2,4 MB and is loading considerably faster!

I am happy for now but if anyone has another idea/suggestion I would like to hear it. :)

**Comment by hokein** [comment]
@handyplayer13 
Theoretically, you could use/implement any node libraries that convert rgba values to a png. `Jimp` is not a must here. Unfortunately, I can't recommend any libraries as I don't have much experience about it neither.

I'm closing it as this is not an issue of greenworks and you have figured out a solution. Suggestions are always welcome.
