### ISSUE TITLE
Works for latest steamWorks (1.40) ?

### ISSUE THREAD

**Issue by 80prozent** [greenheartgames/greenworks#146]
Hey

I am planning on publishing a NW.js game on steam.

Now this lib looks exactly like what i need for the task. Thanks for creating it!

Going over the instructions, i see that your General Prerequisties says that the Steamworks SDK 1.38a is needed, but what is available on steam now is the Steamworks SDK 1.40.

Was just wondering if this is tested with latest steamworks api, or if there is a way to obtain the steamworks verison that is needed.

**Comment by hokein** [comment]
@80prozent 
The latest Greenwork [release](https://github.com/greenheartgames/greenworks/releases) is built with Steamworks SDK 1.40. 

The readme is stale, I will update it. Thanks for the report.

**Comment by 80prozent** [comment]
Thanks for the info. Will go ahead and try to use your lib. 

Thx
