### ISSUE TITLE
Support for Interfaces_and_method

### ISSUE THREAD

**Issue by Dairnon** [greenheartgames/greenworks#147]
https://developer.valvesoftware.com/wiki/Steam_Web_API#Interfaces_and_method

I'd like to be able to grab data for other games info within a players steam account. These methods here seem to allow alot of that functionality, and it be nice to be able to use them!

**Comment by hokein** [comment]
Steam web APIs are out of scope for Greenworks. We only support Steam SDK APIs.

For web APIs, I think it is relatively easy to use them directly in node.js (e.g. basically send web requests and receive results).
