### ISSUE TITLE
Multiple steam accounts?

### ISSUE THREAD

**Issue by DVassilev** [greenheartgames/greenworks#148]
Is it possible to use this on multiple steam accounts? If not, what would be the minimum specs that would be necessary to be able to use this in order to spin up virtual machines for each account? Thanks

**Comment by hokein** [comment]
I don't think steam supports multiple steam account at one time. From the [FAQ](https://support.steampowered.com/kb_article.php?ref=8963-EIKC-3767)

> Yes, you can access different Steam accounts from one computer. However, you may only access one account at a time.
