### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by Suvitruf** [greenheartgames/greenworks#149]
I have greenworks-win64.node in lib folder. But when I try to run app:

```
const greenworks = require('./greenworks');
greenworks.init();
```

I get error:

```
Error: The specified module could not be found.
\\?\D:\texts\Sources\Nodejs\main\teststeam\lib\greenworks-win64.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\texts\Sources\Nodejs\main\teststeam\greenworks.js:17:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
```

P.S. I'm using greenworks-v0.10.0-nw-v0.22.3-win-x64.zip from https://github.com/greenheartgames/greenworks/releases

**Comment by hokein** [comment]
@Suvitruf Can you list your sample code directory and paste it here? It would be helpful to figure out the reason.

**Comment by Suvitruf** [comment]
![dir_list](https://user-images.githubusercontent.com/1946939/27924601-8e662772-628a-11e7-9145-eca6aaa67c7a.png)

But, mb I've just did something wrong. Can I use NW binaries in node.js server application?

**Comment by hokein** [comment]
The directory looks reasonable to me.

> Can I use NW binaries in node.js server application?

No, you can't use the NW prebuilt binaries for node.js server application. You have to build the binary by your self. I think this is the reason causing the error.

**Comment by Suvitruf** [comment]
How ca I do this?

Is it enough?
```
# Change to the Greenworks source directory
cd greenworks
# Install the dependencies
npm install
# Configure gyp project
node-gyp configure
# Build Greenworks addon
node-gyp rebuild
```

And, should I build it on each platform separately? I need it on both Win and Linux.

**Comment by hokein** [comment]
Yes, but make sure you have prepared the environment: https://github.com/greenheartgames/greenworks#general-prerequisties.

> And, should I build it on each platform separately? I need it on both Win and Linux.

Yes, you need to build it separately.

**Comment by Suvitruf** [comment]
Ok, thanks, I will try.

But, are you planning to make prebuilt nodejs releases?

**Comment by hokein** [comment]
>  are you planning to make prebuilt nodejs releases?

We have any plan yet as many of our users are using nw.js/electron prebuilt binaries. But if there are more people requesting it, we might consider adding nodejs release.

I'm closing the issue now.
