### ISSUE TITLE
Using on server without running Steam

### ISSUE THREAD

**Issue by Suvitruf** [greenheartgames/greenworks#150]
I want to use this lib for user auth validation (`decryptAppTicket`).

But, with this code:
```
const greenworks = require('./greenworks');
greenworks.init();
```

I have error:
```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
/var/unnyworld/test-steam/test-steam/greenworks.js:102
    throw new Error("Steam initialization failed. Steam is not running.");

```

But I have steamclient.so in lib folder. Any tips?

P.S. Ubuntu_x64. I've built greenworks-linux64.node and steamclient.so by myself

**Comment by hokein** [comment]
Normally, Greenworks are requiring Steam client running. For this case, I'd suggest you removing the `init()` function call, and using the decrypting APIs directly. However, I'm not sure whether it will work. 

@arch would you mind sharing your experience here? since you used greenworks to build a nodejs server #93.

**Comment by Suvitruf** [comment]
Looks like it did the trick, but...
From Steam I got decryption key, and it's 64 bytes. So, when I try to use it, I get error `The key length is not matched`, and `greenworks.EncryptedAppTicketSymmetricKeyLength` shows me that key should be 32 byte length.

**Comment by Suvitruf** [comment]
https://github.com/greenheartgames/greenworks/blob/245790a8273ea60545d900f17c6e13a77abda7cb/docs/authentication.md

`ticket`, `key` are `Buffer`s. But what should I pass to it? byte array? string? hex string?

**Comment by hokein** [comment]
> ticket, key are Buffers. But what should I pass to it? byte array? string? hex string?

Should be a byte array, e.g. `key = new Buffer([0x0a, ..., 0x0b]).`

**Comment by Suvitruf** [comment]
But where can I get this array for secret key?
On Steam https://partner.steamgames.com/apps/sdkauth/ I have just string (btw, it's 64 length long). Is it base64 string?

**Comment by Suvitruf** [comment]
If I change steam_appid to 480 like in spacewar Steam demo, and use this key https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamUserTest.cs#L245, I can decrypt ticket. But when I change steam_appid to my actual app id (and change byte array for my key) it doesn't work )=

If I setup steam_appid with garbage like 11111111111111, encrypt method still working, but decrypt obviously not, like wtf?

I mean, should we fully publish the game to test decryption? Or should we make any special steps to test it?

**Comment by Suvitruf** [comment]
Hm, looks like we should upload at least 1 build to steam to make it works. Now, at least it works in Unity3d (with C# lib).

But if I pass same vals as byte array in your lib I get this error:
`Segmentation fault (core dumped)`

**Comment by hokein** [comment]
Could you paste the stack trace log here? You can google "node addon core dump" to see how to dump the C++ stack trace.

**Comment by Suvitruf** [comment]
Sorry, my bad.
I've used it like this: `greenworks.isTicketForApp(decrypted_app_ticket, greenworks.getAppId())` and it crashes 'cause of `greenworks.getAppId()`. If I change it to constant it works well.

**Comment by Nestoro** [comment]
> Looks like it did the trick, but...
> From Steam I got decryption key, and it's 64 bytes. So, when I try to use it, I get error The key length is not matched, and greenworks.EncryptedAppTicketSymmetricKeyLength shows me that key should be 32 byte length.

@Suvitruf 
how did you solve this?
if i try to use a 32 byte key my getEncryptedAppTicked exits with:

`Error on getting encrypted app ticket.`
