### ISSUE TITLE
greenworks-win64.node module could not be found.

### ISSUE THREAD

**Issue by Skeltpr** [greenheartgames/greenworks#152]
Whenever I attempt to get the greenworks module (_by doing require('./greenworks')_) in my Electron project, the following error occurs:

> Error: The specified module could not be found.
> \\?\\C:\\Users\\[User]\\Desktop\\electron-v1.7.2-win32-x64\\resources\\app\\lib\\greenworks-win64.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
>     at Object.Module._extensions..node (module.js:598:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\[User]\Desktop\electron-v1.7.2-win32-x64\resources\app\greenworks.js:17:18)
>     at Object.<anonymous> (C:\Users\[User]\Desktop\electron-v1.7.2-win32-x64\resources\app\greenworks.js:133:3)

Even in a super simplistic project, this error still appears to occur.
For example:

I am using the latest [prebuilt binary of Greenworks](https://github.com/greenheartgames/greenworks/releases/tag/v0.10.0) for Electron win32 and 64. 
I have downloaded [Electron v1.7.2 Beta](https://github.com/electron/electron/releases/tag/v1.7.2) 

Within the electron project, I have created a small app in:
electron-v1.7.2-win32-x64 > resources > app

It is set up like:
 \- greenworks.js
 \- index.html
 \- main.js
 \- package.json
 \- steam_appid.txt
 \- lib/
 \- \- greenworks-win32.node
 \- \- greenworks-win64.node
 \- \- steam_api.dll
 \- \- steam_api64.dll

Both steam_api.dll and steam_api64.dll are from the 1.40 Steam SDK

In the main.js, it's just:

> const {app, BrowserWindow, Menu} = require('electron');
> 
> let mainWindow;
> 
> app.on('ready', () => {
> 
>   mainWindow = new BrowserWindow({
>       height: 600,
>       width: 800
>   });
> 
>   mainWindow.loadURL('file://' + __dirname + '/index.html');
> 
>   const template = [
> 		{
> 			label: 'Edit',
> 			submenu: [
> 				{role: 'undo'},
> 				{role: 'redo'},
> 				{type: 'separator'},
> 				{role: 'cut'},
> 				{role: 'copy'},
> 				{role: 'paste'},
> 				{role: 'selectall'},
> 				{role: 'toggledevtools'}
> 			]
> 		}
> 	]
> 
> 	const menu = Menu.buildFromTemplate(template)
> 	Menu.setApplicationMenu(menu);
> });

and the index.html is:

> \<h1\>Hello World!\</h1\>
> 
> \<script>
> try {
> 	require('./greenworks');
> } catch(e) {
> 	console.log(e);
> }
> </script>

Running the Electron executable and opening the dev tools displays the error.

**Comment by Elendir** [comment]
Hello Skeltpr,

I'm having the exact same issue. 
No problem on osx, and I didn't test for linux.

Let me now if you find some workaround.

**Comment by fantasydr** [comment]
Same here. If the dll is not properly placed, the error message is
```
Uncaught Error: Cannot find module './lib/greenworks-win64'
```

If it is placed properly, then it cannot be loaded neither. The error message is:
```
Error: The specified module could not be found.
\?\C:\<some_path>\greenworks-win64.node
```

**Comment by hokein** [comment]
Thanks for pointing out @fantasydr. Unfortunately, we can't control the error message being printed here as it is from the node kernel.
 
The `sdkencryptedappticket` dynamic library is required, please see  https://github.com/greenheartgames/greenworks#general-usage-requirements

I'm closing it out as it is resolved.

**Comment by elamaunt** [comment]
Hello! 
I'm having the same issue.

I've tried all what you said. But it always fails on loading node module. 
I copied all libs from steam sdk 1.40 and downloaded nodes files for this sdk here https://github.com/greenheartgames/greenworks/releases. Also created steam_appid.txt.

Before i fell in the same problem by trying simple "npm install greenworks". Nothing works.
It is always "The specified module could not be found.\\?\Z:\Coding\GoZwebServer\src\PaymentAPI\node_modules\greenworks\lib\greenworks-win64.node"

I use only node.js with express and platform windows 10 x64.
Could you help me please?

**Comment by chuuu** [comment]
@elamaunt Did you find out a workaround?
