### ISSUE TITLE
Is it possible to subscribe to workshop items?

### ISSUE THREAD

**Issue by jhovgaard** [greenheartgames/greenworks#153]
Hi,

I can find the `greenworks.ugcUnsubscribe` method, but I don't see any way of subscribing to items. I believe this is the method I'm looking for: https://partner.steamgames.com/doc/api/ISteamUGC#SubscribeItem

Is the implementation missing, or am I doing something wrong?

Thanks for all your work!

Best,
Jonas

**Comment by Emad88** [comment]
Looking at the source code it seems like it's missing.

**Comment by hokein** [comment]
Yeah, the API is missing.  It makes sense to add this API using https://partner.steamgames.com/doc/api/ISteamRemoteStorage#SubscribePublishedFile.

Note that the link @jhovgaard provided is a new workshop API in Steam SDK, however Greenwork currently is using the deprecated remote-storage APIs for the workshop APIs.

**Comment by patrickklug** [comment]
@jhovgaard just curious about your use case. We didn't implement this method because players are subscribing through the steam client. Did you make your own workshop browser in-game or why do you need to be able to subscribe from the game itself?

**Comment by jhovgaard** [comment]
@patrickklug Yes, I wanted to make an in-game browse feature as seen in Banished: https://www.youtube.com/watch?v=lf9iB-4t96E

I eventually ended up with the approach you mention, asking the player to install via Steam, but I think it would be a nice future improvement to subscribe in-game too.

**Comment by patrickklug** [comment]
I see. neat idea. we didn't bother with it because the player can just use the steam overlay to browse and install mods while in the game too. (though they do have to restart the game for it to sync anyway, so in-game subscribing is IMO of limited use).

**Comment by jhovgaard** [comment]
Ahhh make sense. I'm using Electron, so the Steam overlay isn't an option right now. But I agree, I ended up with a solution where Electron calls out externally and opens a browser pointing at the Workshop. It works quite well.

Thanks! Feel free to close the issue :-)

**Comment by hokein** [comment]
OK, looks like we get another option here, and the `ugcUnsubscribe` API is not useful as we expect. So I'm closing this issue as it won't fix. 

We can reconsider to add it if others raise it in the future.

**Comment by GrosTon1** [comment]
Well, I actually managed to get it working just copy/pasta'ing the unsubscribe things.
Do you want me to do a PR ?

**Comment by podrivo** [comment]
Hello @hokein! Would it make sense to add `ugcSubscribe` to greenworks? Some games need to be subscribed in order to download the files, so it would be really helpful.
