### ISSUE TITLE
steam overlay notification position cannot be changed

### ISSUE THREAD

**Issue by HolzerBane** [greenheartgames/greenworks#156]
Hi, I have a steam application that uses greenworks with electron. I can successfully initialise the steam API and the steam overlay notification ("toast") shows fine but I cannot set the position where it appears. 
I am using SteamUtils()->SetOverlayNotificationPosition(k_EPositionBottomLeft) right in the InitAPI function after the steam api successfully initialises but the steam notification still pops up in its default location, bottom right.
I tried using the same steam sdk with a qt application and it works fine.
I also tried exposing the SetOverlayNotificationPosition() function to js and calling it from my electron app but it makes no difference. 
Interestingly I found that if I run my electron app outside of steam the notification doesn't show but it shows if I run the qt application outside of steam.
I am using greenworks 0.8.0 and electron 1.4.15.

**Comment by hokein** [comment]
The overlay might not work perfectly in Greeworks, which is a known issue. And currently we don't support set notification position officially (but we are always happy to accept the PR).

I'm closing it now, please feel free to reopen.
