### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by Zamiell** [greenheartgames/greenworks#158]
On [this page](https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md):

1)

```
Provide the Steamworks SDK dependency to Greenworks by following the steps from the "General Prerequisties" section earlier on the page ( You need to create and populate the node_modules/greenworks/deps/steamworks_sdk folder.).
```
This should be:
```
Provide the Steamworks SDK dependency to Greenworks by following the steps from the "General Prerequisties" section earlier on the page. (You need to create and populate the `node_modules/greenworks/deps/steamworks_sdk` folder.)
```

2)

```
cp node_modules/greenworks/sample/electron/main.js renderer.js
```

This should be:

```
cp node_modules/greenworks/samples/electron/main.js renderer.js
```

3)

This page should have a step added somewhere (not exactly sure where) that instructs users that if they are using `electron-builder` (the primary electron build/release framework), then they should add the following to their `package.json` file:
```
  "build": {
    "files": [
      "!node_modules/greenworks/deps/**/*"
    ]
  },
```
The purpose of this is that the dependencies don't get included or compiled in the actual end-user release.

This information should probably also ALSO go in the "Gotchas" section.

Source: From the `electron-builder` developer: https://github.com/electron-userland/electron-builder/issues/2109

**Comment by hokein** [comment]
@Zamiell Thanks for the detailed update! It is very close to a PR, would you mind sending a PR to the greenworks repo?

**Comment by Zamiell** [comment]
Well I didnt do a PR because of number 3. Feedback on number 3 above?

**Comment by hokein** [comment]
@Zamiell  I don' have strong opinion about number 3 as long as it is mentioned somewhere, I'd prefer to build-instructions-electron.md.

**Comment by Zamiell** [comment]
Ok, see #164

**Comment by hokein** [comment]
Closing it as #164 has fixed it.
