### ISSUE TITLE
Module Not Defined Using Mac Binary

### ISSUE THREAD

**Issue by quantumproducer** [greenheartgames/greenworks#162]
I am using nw.js latest SDK version: nwjs-sdk-v0.25.4-osx-x64
`node -v : v8.6.0`

I include this in my html:

`<script src="greenworks.js"></script>`

I copied the Steam & greenworks files to ./lib

I get 'module not defined' when trying to do module.exports:

<img width="517" alt="screen shot 2017-10-03 at 15 12 23" src="https://user-images.githubusercontent.com/11827932/31144096-9abc0fb0-a84d-11e7-94b7-a4bcf43e6cdc.png">

I tried commenting out that line and doing {].exports as I saw this in another thread, but this still does not work.

**Comment by hokein** [comment]
@quantumproducer Do you use the prebuilt Greenworks binary? Current we don't provide prebuilt binary for nw.js v0.25.X. You should build the binary from the source if you need to run Greenworks for nw.js v0.25.X.

**Comment by quantumproducer** [comment]
@hokein I will try version 0.23.7 of nw.js with the matching greenworks binary.

Is that what the error indicates to you, just to be sure -- not some node configuration issue on my end?

**Comment by quantumproducer** [comment]
@hokein I still get this same error with 0.23.7 of nw.js.

I also got this warning "your profile is using a newer version of nw.js" when I started the app.
Strangely, when I tried running newer nw.js with Steam enabled I get this:

```
Uncaught ReferenceError: module is not defined
    at greenworks.js:131
engine_rev.js:12 Steam API has been initalized.
```

How could that happen?

**Comment by hokein** [comment]
I assume the author has figured out the reason, closing it now, please feel free to reopen it .

**Comment by quantumproducer** [comment]
Hello, I found the issue is because of the saved application data on my machine was using a different version.
I had to delete that application data folder.
