### ISSUE TITLE
compiled against a different Node.js version using

### ISSUE THREAD

**Issue by cimpdev** [greenheartgames/greenworks#165]
can u help me?

module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '\\?\C:\Users\test\Desktop\awefwef\lib\greenworks-win64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing

the module (for instance, using `npm rebuild` or`npm install`).

**Comment by remvst** [comment]
(assuming you're using the prebuilt library)

What version of Electron/NW.js are you using, and with what version of greenworks? Ideally, you would follow the versions that are listed in the release:
> Greenworks complied for NW.js v0.23.7 & Electron v1.8.0 Beta with Steamworks SDK 1.41

**Comment by hokein** [comment]
As @remvst pointed out, you are likely using an inappropriate prebuilt greeenwork version on NW.js or Electron.
