### ISSUE TITLE
Can SteamCMD work as the normal steam client in the linux server?

### ISSUE THREAD

**Issue by micheal-death** [greenheartgames/greenworks#169]
I was trying to call "greenworks.initAPI()" with an instance of SteamCMD running in the linux server, but got these errors:
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

**Comment by hokein** [comment]
From the error messages, it looks like greenworks thought the Steam client is not running. Could you try `greenworks.init()`? That API provides better error message.

**Comment by micheal-death** [comment]
@hokein 
Trying `greenworks.init()`, it seems the same errors:
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
/home/wwwroot/greenworks-0.11.0/greenworks.js:102
    throw new Error("Steam initialization failed. Steam is not running.");
    ^

Error: Steam initialization failed. Steam is not running.
    at EventEmitter.greenworks.init (/home/wwwroot/greenworks-0.11.0/greenworks.js:102:11)
    at Object.<anonymous> (/home/wwwroot/greenworks-0.11.0/test/test.js:19:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**So, is there any way that i can use `greenworks.getAuthSessionTicket` without running a steam client?**

**Comment by hokein** [comment]
You can find more details at #150. @Suvitruf, @artch could you share your experience on using Greenworks on linux server?

**Comment by artch** [comment]
I have never tried to do that with SteamCMD, only with a normal Steam client which just works.

**Comment by hokein** [comment]
Thanks for @artch's rely.

I'm closing it now, please feel free to reopen it if you still have questions.

**Comment by Awpteamoose** [comment]
What do I do if I can't run a normal Steam client? I need to get the ticket from `greenworks.getAuthSessionTicket()` to use an API in a steam game.
