### ISSUE TITLE
Please update to the latest NW.JS

### ISSUE THREAD

**Issue by maxii1996** [greenheartgames/greenworks#171]
Hi. Please. can someone make a build for nwjs-v0.26.6 please?

The v0.23.7 it has a problem with my game because it says that my NW.JS version is newer than v0.23.7 (i need integrate steam with rpgmkrMV) and also the 0.23.7 it has a Bug when u close the Game, The Game doesn't close at all. It's still opened on background.

Please and thanks

**Comment by hokein** [comment]
@maxii1996 thanks for raising it up.
I'm still waiting for the chromium 61 upgrade for electron before making a new Greenworks release,   electron should be close to a next major release.

But it is sensible to release a new Greenworks version for nwjs-v0.25 and nwjs-v0.26, I will probably make a release this week.

**Comment by maxii1996** [comment]
Oh that will be great @hokein I really need it. I want to integrate my game to enable the achievements and other things :)

I only use nwjs. electron i've never used it xD

But Thanks since now. I'll waiting it :D

**Comment by hokein** [comment]
The latest version has been released now.
