### ISSUE TITLE
Error on writing file on Steam Cloud.

### ISSUE THREAD

**Issue by riadd** [greenheartgames/greenworks#173]
Hello, we recently implemented Steam Workshop support and have run into a problem on some machines, where the upload through our game fails with the error message.

`Error on writing file on Steam Cloud.`

We're using

`greenworks.saveFilesToCloud`

I checked the steam SDK and I could not figure out what the problem is. The file is not too large, the path looks fine, the user quota has more than enough space, fire wall is turned off.. yet the function returns immediately with that error message on some machines.

I'm not sure if the problem is with greenworks or steam, but maybe somebody has an idea how to debug this or has seen a similar problem.

Thanks

**Comment by hokein** [comment]
hmm, I can't tell you the exact reason.

The error message indicates that the `SteamRemoteStorage()->FileWrite` API fails to write the file.
Unfortunately, this SteamSDK API doesn't give more information about the failure (only a `bool`) :(

**Comment by riadd** [comment]
Thanks for the reply! I'll try to get some help at the steam forums :(

**Comment by hokein** [comment]
I'm closing this issue now, feel free to reopen it if you have more details.

**Comment by riadd** [comment]
I checked the user quota which was fine, but I didn't check the server quota which by default only allows up to 5 files to be uploaded. Completely my mistake. Posting it here in case anybody else is a stupid as I am. Sorry for stealing your time.

**Comment by hokein** [comment]
@riadd Good finding, thanks for sharing it. Is the behavior documented somewhere in SteamSDK?

**Comment by riadd** [comment]
I don't think the default values are documented, but generally the quota is documented.

**Comment by mirrorlink** [comment]
I'm having trouble with it. What is the path I should passs to saveFilesToCloud method?

I'm using greenworks.saveTextToFile('savegame_0') for example when saving files

**Comment by mirrorlink** [comment]
So, after some testning with two computers it seems this is working. For further reference, if you use the method saveTextToFile you dont need to use saveFilesToCloud. And it will be automatically sinced if its enabled =)
