### ISSUE TITLE
How to get Steam user nickname.

### ISSUE THREAD

**Issue by MlgmXyysd** [greenheartgames/greenworks#174]

**Comment by hokein** [comment]
You can use `SteamID.getNickname()`.

**Comment by MlgmXyysd** [comment]
Uncaught ReferenceError: SteamID is not defined

**Comment by MlgmXyysd** [comment]
<script src="main.js"></script>
<script>require('./greenworks.js');SteamID.getNickname();</scipt>
main.js in /samples/nw.js

**Comment by hokein** [comment]
You need to retrieve the `SteamID` object via [`greenworks.getSteamId()`](https://github.com/greenheartgames/greenworks/blob/master/docs/setting.md#greenworksgetsteamid).

And also make sure you have initialized Greenworks, see https://github.com/greenheartgames/greenworks/tree/master/docs#apis.

**Comment by MlgmXyysd** [comment]
okay,
BTW,Can you build a new version for nwjs-0.24.3 please?

**Comment by hokein** [comment]
Theoretically, you can use the nwjs v0.24.4 prebuilt greenworks on nwjs v0.24.3. It should work.
