### ISSUE TITLE
"Error on saving file on local machine"

### ISSUE THREAD

**Issue by jhovgaard** [greenheartgames/greenworks#178]
Hi guys!

For a long time I've been having multiple players complaining about mods not being installed after subscribing. It seems to be strictly Windows (64 bit). Whenever there's a call to `greenworks.ugcSynchronizeItems`, it will instantly return the following error "Error on saving file on local machine". 

I believe this is the line: https://github.com/greenheartgames/greenworks/blob/master/src/greenworks_workshop_workers.cc#L357

For the affected players I've confirmed the following:

- Plenty of free disk space
- No third party AV, only Windows Defender
- Running the electron process as administrator doesn't change anything.

My game is saving files to the exact same directory using `fs.writeFile` with no problems.

Any idea what can be causing this?

Thanks for reading!
Jonas

**Comment by hokein** [comment]
@jhovgaard Thanks for reporting it.

I suspect the root cause is at https://github.com/greenheartgames/greenworks/blob/master/src/greenworks_workshop_workers.cc#L85, the`GetAbsoluteFilePath` doesn't generate the legal format file path on Windows (we should use `\` as file separator instead of `/` ) .

**Comment by jhovgaard** [comment]
Hi again,

After looking closer at the paths I figured out how to reproduce it: include special characters like Nordic Æ, Ø and Å in folder names. It probably fails with other non-english characters too.

**Comment by Noobulater** [comment]
Also having this issue

**Comment by Noobulater** [comment]
You can resolve this by just specifying the full path yourself. (was trying to use a relative path, don't do that, just use path to find out exactly where to place the file)

**Comment by patrickklug** [comment]
This could explain some issue we've been seeing too. If anyone has a clue how to fix this, we'd love a patch.

**Comment by Eyesiah** [comment]
Was any progress made on this issue? I have users also reporting it, and I was able to reproduce it by creating a steam library at `D:\SteamLibraryÆØÅ` and installing our game there. But our game passes in the absolute path to `ugcSynchronizeItems`, so I haven't been able to work around it.

**Comment by hokein** [comment]
I'm happy to prepare a fix for it, is there any volunteer to test it?

**Comment by Eyesiah** [comment]
Sure, I'll happily test it, though I can't build greenworks myself. But if
you prepare a standalone win32 build I can test it

**Comment by jhovgaard** [comment]
I’m ready to rest on all platforms too.
