### ISSUE TITLE
Overlay on OSX

### ISSUE THREAD

**Issue by ThomasMorrison** [greenheartgames/greenworks#179]
It seems like the last time the Steam overlay worked on OSX was on nwjs 0.12.1 (please correct me if I am wrong).

I have a build of this working just fine, however, retina screens (which are now pretty much standard on macs) do not display the overlay properly, see below:

My Sample App:
<img width="741" alt="screen shot 2018-01-20 at 9 23 51 pm" src="https://user-images.githubusercontent.com/4522962/35190134-724f84ae-fe28-11e7-8d82-dc78e28893e5.png">

In the app "Super Game Jam" 
<img width="1435" alt="screen shot 2018-01-20 at 9 23 07 pm" src="https://user-images.githubusercontent.com/4522962/35190139-8c8d2c68-fe28-11e7-91c0-656ce3b57909.png">

In a gif posted here:
https://github.com/greenheartgames/greenworks/issues/45#issuecomment-138500239

As is fairly obvious, the overlay is not respecting the pixel density of the screen. If you move the application to a screen with a pixel density of 1, everything looks fine.

It seems like this is known behaviour, so:
Am I to assume this is more or less un-fixable?

**Comment by hokein** [comment]
@ThomasMorrison Thanks for the report. 
Unfortunately, for the overlay issue, your assumption is right. I don't think there is much we can do in Greenworks side :(, so I'm closing it now.
