### ISSUE TITLE
greenworks.isGameOverlayEnabled() always returning "false".

### ISSUE THREAD

**Issue by janpetersen** [greenheartgames/greenworks#18]
The method `greenworks.isGameOverlayEnabled()` always returns "false".

Tested with version 0.4.0 and 0.4.1.

**Comment by hokein** [comment]
The `isGamerOverlayEnabled` API is implemented by `SteamUtils()->IsOverlayEnabled()`, so the result relies on Steam. Please check your Steam.

**Comment by janpetersen** [comment]
Whatever I tried, I never got this to return "true". Other API methods, like "isCloudEnabled()" and "isCloudEnabledForUser()" work fine and always return the correct value.

Does this work with your games? I did not find anything on Google regarding a possible bug in the SteamUtils API.

**Comment by hokein** [comment]
As far as I know, the game GDT doesn't use this API. I test the API on GDT, but failed by returning `false` even the `overlay` feature is enabled.

Actually I have no much idea about this, since this is more like a Steam API issue.

**Comment by jportoles** [comment]
I can confirm that still today `isGameOverlayEnabled` always returns false no matter what, however the `game-overlay-activated` EventEmitter works properly, so you can get around this issue by calling a method that opens the overlay, and then listening to the event; if the event doesn't fire shortly after then the overlay is probably disabled or not initialized.
