### ISSUE TITLE
ugcGetItems limited to 50 records

### ISSUE THREAD

**Issue by jhovgaard** [greenheartgames/greenworks#180]
Hi again :-)

I'm struggling with `greenworks.ugcGetItems` not allowing me to grab more than 50 records. Is there any way to get all available `fileName` for my workshop?

Thanks again!

Jonas

**Comment by hokein** [comment]
Yeah, this is a bug of the API. The current implementation only returns the first page of the items (https://github.com/greenheartgames/greenworks/blob/master/src/greenworks_workshop_workers.cc#L288), which is 50 items/per page.

One possible fix is to add an option (`page`) to the `ugcGetItem` API.

**Comment by Burnett01** [comment]
Back in December I needed that functionality so I quickly wrote it.  Been using it for a while now. 

#181  

If the pull-request doesn't fit the quality/coding guidelines feel free to decline it. 

Cheers, Steve.
