### ISSUE TITLE
For Mac - expected file in "/steam_appid.txt" (using electron-builder)

### ISSUE THREAD

**Issue by Kamadake** [greenheartgames/greenworks#183]
So I'm using electron-builder to do my steam application (based off szwacz/electron-boilerplate) and making Windows build of my application has no problems. But when I do make my Mac build, I'm getting the error that it's expecting a file in "/steam_appid.txt", with the root directory symbol. My steam_appid can be found in name_of_application.app/Contents/steam_appid.txt.

I know that if I changed in greenworks.js:
`appId = fs.readFileSync('steam_appid.txt', 'utf8');`
to
`appId = fs.readFileSync(path.join(__dirname, 'steam_appid.txt'), 'utf8');`

it does go to the final error message where it asks whether the App ID is correct. maybe something is changing the working directory for me during the build process on mac?

**Comment by hokein** [comment]
@Kamadake Looks like you have solved the issue? Do you mind sharing your experience? Thanks!

**Comment by Kamadake** [comment]
The weird thing is that when I was launching the .app file directly, for some weird reason it's expecting steam_appid.txt to be at the root location, literally "/steam_appid.txt". 

Then a colleague of mine suggested running the executable file found inside the package's contents. Can't remember the path right now cause I'm on Windows but the executable has the same name as your package. When I did that, it expected steam_appid.txt to be inside the User's Home directory. It's weird but this is only necessary until you actually push your game on Steam.

**Comment by hokein** [comment]
@Kamadake Thanks for sharing it!

**Comment by skymen** [comment]
I just mentioned this issue in another issue and gave some more info on what to do, hope this helps
