### ISSUE TITLE
Error module

### ISSUE THREAD

**Issue by S1ROZHA** [greenheartgames/greenworks#188]
![image](https://user-images.githubusercontent.com/20708709/38527745-219d736a-3c65-11e8-9a3a-1700b76ba48b.png)

**Comment by hokein** [comment]
Please provide the version of greeenworks/nodejs you are using. I suspect you are using a mismatched greenworks binary.

**Comment by S1ROZHA** [comment]
0.1.0

**Comment by hokein** [comment]
I don't think we provide support for v0.1.0, which is pretty old.
