### ISSUE TITLE
Retrieving a File Directory of Steam Cloud

### ISSUE THREAD

**Issue by Noobulater** [greenheartgames/greenworks#189]
First of all, thanks for sharing your work, its helping me immensely
  
Is there way to find a list of files on the steam cloud? I only ask because the way I've seen it done before doesn't seem to be exposed in the binary releases (Looking for GetFileListFromServer, or getFileCount from SteamRemoteInterface)

Thanks

**Comment by hokein** [comment]
AFAIK, we don't expose the `GetFileListFromServer` or `getFileCount` yet, I think it is reasonable to add it in greenworks.
