### ISSUE TITLE
Request new API method: greenworks.isGameOverlayActive()

### ISSUE THREAD

**Issue by janpetersen** [greenheartgames/greenworks#19]
It would be nice to have an API method like `greenworks.isGameOverlayActive()` that tells me about whether or not the Steam overlay is active.

Regarding [Valve's documentation](https://partner.steamgames.com/documentation/game_overlay#callbacks), there are "signals" being sent on certain interactions of the user:

> **Communication from the overlay to your game**
> The following signals (callbacks) are sent from Steam to your game, based on user action in the overlay:
> `GameOverlayActivated_t` - posted when game overlay activates or deactivates. The game can use this to be pause or resume single player games.

According to the file `steam/isteamfriends.h`, the value passed will either be true or false.

Or there could be event handlers like "onGameOverlayActivated()" and "onGameOverlayDeactivated()" that trigger when these signals get submitted.

But I don't know whether there is a general "signal listener" in the Greenworks module yet. This would be quite useful, too, because there are a lot of signals that could be handled.

Perhaps you could take this into consideration for your next release.

Thanks!

**Comment by hokein** [comment]
The APIs look good to me.

`isGameOverlayActive()` is a synchronized API, which is not aligned with Steam's signal formalism. We can support it through node's `EventEmitter`.

**Comment by janpetersen** [comment]
That would be very nice! :)
