### ISSUE TITLE
NODE_MODULE_VERSION conflicts

### ISSUE THREAD

**Issue by Matt-Maerz** [greenheartgames/greenworks#190]
Uncaught Error: The module '\\?\C:\Users\XXXX\AppData\Local\Temp\nw4784_9415\lib\greenworks-win64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Is this a bug or is this my stupidity?
Any HELP Please?

**Comment by hokein** [comment]
The error message has already pointed out the reason: you are using a mismatched greenwork binary. Please make sure you download the correct greenwork prebuilt binary for your corresponding nw.js version.
