### ISSUE TITLE
Overlay Not Work NW.JS 0.29.4 GREENWORKS 0.13.0

### ISSUE THREAD

**Issue by mrdev023** [greenheartgames/greenworks#196]
I'm use NW.js 0.29.4 with greenworks 0.13.0 but the Overlay not work I'm use a webgl context and the "chromium-args": "--in-process-gpu --enable-webgl --ignore-gpu-blacklist" in package.json.

**Comment by mrdev023** [comment]
I'm try this but not work :'(
I'm try to run greenworks.activateGameOverlay('Friends') and return undefined but the overlay does'nt display.

**Comment by hooker99** [comment]
I can't test anything right now, my problem is here: https://github.com/greenheartgames/greenworks/issues/193 :D.

You have to wait for answer 👯‍♂️

**Comment by hokein** [comment]
@mrdev023 It is a known issue #16, overlay doesn't work properly on chromium-based steam integration, e.g. nw.js and electron -- it only works on a specific version under a particular set of flags.

Unfortunately, this is not an issue which can be solved from Greenworks side.

**Comment by genesix-eu** [comment]
I think it should be written on "Build Instructions (NW.js)" page that you need to start game thru steam (add it as non-steam game to library and use appid 480 before you got your own) to make steam overlay work. 
Now at least it opens, but is still bugged...
