### ISSUE TITLE
Linkage error

### ISSUE THREAD

**Issue by Baccanno** [greenheartgames/greenworks#20]
After some research it seems that greenworks is unable to link the dll for steam.
(using sdk 1.32)
it says
```
Error: The specified procedure could not be found.
C:\[...]\win64\data\lib\greenworks-win64.node
```

I tried both steam and steam64 dll in the lib folder, the data folder and the win64 folder ( in case it was a path issue ). I saw somewhere that it might be related another to a missing dll.

Thnaks for your help and great job !

**Comment by Baccanno** [comment]
I renamed the main executable back to nw.exe and it worked. There is no mean to rename it ?

**Comment by hokein** [comment]
I suppose that this is no related to Greenwork. Instead, it's a NW.js issue. See nwjs/nw.js#199, and its [wiki](https://github.com/nwjs/nw.js/wiki/Using-Node-modules) says:

> on Windows the engine's executable file must have the name nw.exe for addons to work (i.e. you cannot rename nw.exe if you need any addon-containing modules). They use parts of the engine to sustain their execution.

It might be fixed in nw13.

**Comment by Baccanno** [comment]
Allright :) Thanks for the highlight !
