### ISSUE TITLE
Tags are not saved with updatePublishedWorkshopFile and publishWorkshopFile

### ISSUE THREAD

**Issue by Emad88** [greenheartgames/greenworks#205]
Workshop files saved or updated have no tags.
I've tried looking at the code but I couldn't figure out what's wrong.

For some reason, I don't get errors in the console when they are thrown, so the functions hang forever.  

Not defining `tags `or `app_id `in the `options` object, settings tags to something that is not an array or an array with more than 100 items, they all make the functions hang with no errors.

**Comment by hokein** [comment]
> Not defining tagsor app_idin the options object, settings tags to something that is not an array or an array with more than 100 items, they all make the functions hang with no errors.

That's weird. There should be exceptions thrown for these two cases.

See
* https://github.com/greenheartgames/greenworks/blob/dd93d68d81bc1cae7d544f92dc78d456a4a59fc4/src/api/steam_api_workshop.cc#L140
* https://github.com/greenheartgames/greenworks/blob/dd93d68d81bc1cae7d544f92dc78d456a4a59fc4/src/api/steam_api_workshop.cc#L147

**Comment by hokein** [comment]
Closing it until more information is provided.
