### ISSUE TITLE
Electron 3.0.0

### ISSUE THREAD

**Issue by evstafev** [greenheartgames/greenworks#207]
Prebuilt binaries please for Electron 3.0.0

**Comment by Eyesiah** [comment]
Thanks - we're seeing some users report bad sound errors that are fixed in electron 3, so it would be much appreciated.
Electron 4's still in beta so that might be a bit premature?

**Comment by hokein** [comment]
New greenworks binary for electron v3.0.9 has been released.

@Eyesiah this is not premature. In theory, you can use Greenworks electron v4 beta prebuilt binary for all electron v4 versions.
