### ISSUE TITLE
Read Workshop item files?

### ISSUE THREAD

**Issue by frontierpsycho** [greenheartgames/greenworks#209]
I'm trying to write an app that will get the user's workshop items and access their files (I need to extract some metadata from them). 

I'm using this to get the user's workshop items:

```
      greenworksInstance.ugcGetUserItems(
        greenworks.UGCMatchingType.Items,
        greenworks.UserUGCListSortOrder.CreationOrderDesc,
        greenworks.UserUGCList.Subscribed,
        (result) => {
          console.log(result);
          _.each(result, (mod) => {
            // TODO something here            
           });
          });
        },
        (err) => console.error(err),
      );
```

But I can't find a way to read the actual files of each workshop item. The [docs](https://github.com/greenheartgames/greenworks/blob/master/docs/workshop.md) describe a `file` field in `SteamUGCDetails` (the type of the result), but the description of that is 

> String: Represents uint64, file handle

And I can't find how to use it in nodejs. 

Any ideas on how to solve this? Would this require us to change greenworks itself to support it?

Thanks!

**Comment by hokein** [comment]
`ugcGetUserItems` only returns the metadata of the file. To retrieve the file content, I think you'd need `ugcDownloadItem` API using the file handle returned by the `ugcGetUserItems`.

**Comment by frontierpsycho** [comment]
Sorry, I meant to say that I want to do this for _downloaded_ items, I don't want to download them myself.

For anyone else looking for something similar, I think I found my answer (even though I haven't tested it yet): [GetItemInstallInfo](https://partner.steamgames.com/doc/api/ISteamUGC#GetItemInstallInfo). That function is sadly not exposed by greenworks, so I presume I have to do it myself.

**Comment by hokein** [comment]
@frontierpsycho adding this API in Greenworks sounds reasonable to me. Patches are welcome.
