### ISSUE TITLE
Error message "greenworks-linux32.node cannot be found”.

### ISSUE THREAD

**Issue by datexgo** [greenheartgames/greenworks#210]
Hi there.

I have a html5 game for release on Steam that's built using Electron and I want to implement Greenworks for achievement support.

I tried both electron-rebuild and node-gyp ways to integrate Greenworks. Also tried to put greenworks folder in the folder where api is called and imported the greenworks object directly, however faced the same issue - the game crashes on startup with an error message "greenworks-linux32.node cannot be found”.

Tried to download this file separately and put it in greenworks/lib. But the problem persists. I can’t figure out what’s going on wrong on our side, but maybe it’s not related to greenworks, needs clarification.

I'm using the following x64 build:
Greenworks: [v0.10.0 x64]
Steam SDK: [v1.40]
Electron: [v1.6.15]

Folder structure is as follows:

app/
| - - steam_appid.txt
| - - node_modules/
| - - - - greenworks/
| - - - - - - greenworks.js
| - - - - - - lib/
| - - - - - - - - greenworks-linux32.node
| - - - - - - - - greenworks-linux64.node
| - - - - - - - - greenworks-osx64.nod
| - - - - - - - - greenworks-win32.node
| - - - - - - - - greenworks-win64.node
| - - - - - - - - libsdkencryptedappticket.dylib
| - - - - - - - - libsdkencryptedappticket.so
| - - - - - - - - libsdkencryptedappticket64.so
| - - - - - - - - libsteam_api.dylib
| - - - - - - - - libsteam_api.so
| - - - - - - - - libsteam_api64.so
| - - - - - - - - sdkencryptedappticket.dll
| - - - - - - - - sdkencryptedappticket.lib
| - - - - - - - - sdkencryptedappticket64.dll
| - - - - - - - - sdkencryptedappticket64.lib
| - - - - - - - - steam_api.dll
| - - - - - - - - steam_api.lib
| - - - - - - - - steam_api64.dll
| - - - - - - - - steam_api64.lib
| - - public/
| - - - - index.html
| - - electron/
| - - src/

Please tell if I do something wrong.

**Comment by iamwhaler** [comment]
I experience the same issue, please evaluate on this

**Comment by hokein** [comment]
@datexgo looks like you are using a mismatch greenworks, for electron v.1.6.x, you should use Greenworks v0.9.0.
My intuition is this may cause by a mis-configuration, not a real bug of greenworks. 

It would be nice if you could provide a minimal electron app that can reproduce this issue. I will try to take a look.

**Comment by iamwhaler** [comment]
The problem is resolved, it was, as you said, a cause of misconfiguration
