### ISSUE TITLE
(Documentation issue) difference between publishWorkshop and the ugc methods

### ISSUE THREAD

**Issue by chadams77** [greenheartgames/greenworks#212]
I'm having trouble determining what the difference between these is, some extra documentation for workshop methods would be helpful.

**Comment by hokein** [comment]
The best way to distinguish them is to read the steam official [document](https://partner.steamgames.com/doc/api/ISteamRemoteStorage). publishWorkshop is based on the deprecated ISteamRemoteStorage.
