### ISSUE TITLE
getStatInt just hangs forever? 

### ISSUE THREAD

**Issue by jadedResearcher** [greenheartgames/greenworks#217]
I'm trying to figure out how the stats work with greenworks, via the following (included the achievement code so you could see what i was mimicking):

`      greenworks.activateAchievement('i_gave_myself_this_achievement',
          function() { console.log('Activating achievement successfully'); },
          function(err) { console.log('Failed on activating achievement.'); });

     greenworks.getStatInt('totallyfake',
               function(stat) { console.log('got stat back',stat); },
               function(err) { console.log('Failed on getting stat.'); });`

activating the achievement works fine getting the stat hangs forever.

My game is coming soon, but that shouldn't effect getting stats right?

**Comment by MikalDev** [comment]
You are calling getStatInt incorrectly, it does not have callbacks, see the doc:

https://github.com/greenheartgames/greenworks/blob/master/docs/stats.md

**Comment by hokein** [comment]
As @MikalDev mentioned, `getStatInt` is not an async API.
