### ISSUE TITLE
Not working on Electron 4.0.4+

### ISSUE THREAD

**Issue by goldfire** [greenheartgames/greenworks#219]
I'm not sure if this is an Electron issue, a greenworks issue or if there just needs to be a new greenworks build, but everything works on Electron 4.0.3, but upgrading to 4.0.4 or any later version silently fails. No errors are logged, the app just hangs when launching and never appears on screen. I'm not seeing this with a regular Electron app that isn't using greenworks.

**Comment by kaansoral** [comment]
It would be nice if there was a newer prebuilt/compiled Electron version, I've been staying on Electron 3 just because it's so practical to use precompiled greenworks libraries on all platforms

**Comment by hokein** [comment]
The prebuilt greenwork for electron4-beta doesn't work for electron >= 4.0.4, as there was a breaking change (elecltron/electron#16687) in electron v4.0.4.

We have to rebuild Greenworks in order to make it work for electron v4.0.4+.

**Comment by goldfire** [comment]
@hokein Ah, I guess I missed that. Thanks for the info!

**Comment by MikalDev** [comment]
You can build your own .node using the appropriate version of Electron. I have done this in the past for Electron (including and up to Electron 5.0.0.beta-) and it's worked well. In general, it does require that you have an environment set up to do the source compile.
https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md

If you need windows compile tools, you can try this:
npm install --global --production windows-build-tools

**Comment by maflores16** [comment]
@MikalDev are you using windows? I'm having a bunch of problems trying to build it. I think however I was able to fix most of them, and now I get stuck here, which I don't understand. 

```gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Mario\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mario\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Mario\Desktop\greenworks
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
added 122 packages in 12.693s```

**Comment by MikalDev** [comment]
@maflores16 sorry you are having problems! I have built using Windows and OSX. When I did the process, I used the electron-rebuild method rather than the gyp method. Perhaps try that? In the meanwhile, if you let me know which version you need (Electron version, OS, 32-bit, 64-bit, etc.), I can probably either build it or get it for you. I am using this nice build tool for Electron that works with my game engine of choice Construct3 (html5/JS) and working with the dev for the tool, they integrated greenworks *.node, etc. and CI for building *.node for many versions of Electron and OSes. Check it out here: https://efc.armaldio.xyz/ It's in the transition to a new version, but I've been using the old version with greenworks and it works very well.

**Comment by maflores16** [comment]
@MikalDev Thank you so much for your reply, I will try that soon. I've been busy, but I think that certainly helps! I need to learn how to build these myself because it's an important part of my project, but if I can't at all I would appreciate your help. 😄

**Comment by maflores16** [comment]
@MikalDev Okay so after so many days of trying, I had the bright idea of going back on each Steam SDK and bingo.  Version 1.42 works but 1.43 and 1.44 do not work. 

Do you remember what Steam SDK you use to build? I'm not sure if this is a bug with greenworks, the sdk, or just my pc.

**Comment by MikalDev** [comment]
@maflores16 Yes, I'm using version 1.42 (because I suspected that was all that greenworks supported.) I think it would probably be a good idea to update greenworks to later Steam SDK versions at some point.
