### ISSUE TITLE
Support for Enhanced Rich Presence?

### ISSUE THREAD

**Issue by riadd** [greenheartgames/greenworks#222]
Hello, I was wondering if greenworks support enhanced rich presence? Couldn't find a mention in the docs.

https://partner.steamgames.com/doc/features/enhancedrichpresence

**Comment by mastastealth** [comment]
I think [this PR](https://github.com/greenheartgames/greenworks/pull/220) had some of it, but seems to still be in progress.

**Comment by riadd** [comment]
Cool, will wait for that PR to be done.

**Comment by TheRealDannyyy** [comment]
Thanks a lot for adding support for this feature!

**Comment by Zekfad** [comment]
@hokein, this issue can be resolved now.
For future reading [see the docs](https://github.com/greenheartgames/greenworks/blob/master/docs/friends.md#greenworkssetrichpresencepchkey-pchvalue).

**Comment by hokein** [comment]
@Zekfad Great, thanks for the contribution.
