### ISSUE TITLE
Wrong module version. How can I fix it?

### ISSUE THREAD

**Issue by LasseNiermann** [greenheartgames/greenworks#223]
Hey.
I ran into an error while trying to implement greenworks to a project.
It says I am using the wrong nw.js version apparently. Yes, I am aware of #190.
However, how can I fix it? Can I compile the current code somehow or how can I downgrade my nwjs version?
I am quite new to JS.

```
Uncaught Error: The module '\\?\C:\Users\lasse\Documents\DBC\Development\lib\greenworks-win64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

Thank you <3

**Comment by MikalDev** [comment]
You can build your own *.node using the appropriate version of nw.js. I have done something similar in the past for Electron (including and up to Electron 5.0.0.beta-*) and it's worked well. I have not tried for nw.js yet (as I am focused on Electron), but I imagine it will also work ok. In general, it does require that you have an environment set up to do the source compile. https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-nwjs.md

If you need windows compile tools, you can try this (which I had to do for building *.node for Electron):
`npm install --global --production windows-build-tools`

**Comment by LasseNiermann** [comment]
Thank you very much ❤️
