### ISSUE TITLE
Support Electron 5.0.0 (Node 12, ABI 70)

### ISSUE THREAD

**Issue by evstafev** [greenheartgames/greenworks#225]
nan 2.13.2
electron-rebuild 1.8.4

.\node_modules\electron-rebuild\lib\src\rebuild.js:122
`this.ABI = 70; //nodeAbi.getAbi(this.electronVersion, 'electron');`

[errors.txt](https://github.com/greenheartgames/greenworks/files/3114026/errors.txt)

**Comment by MikalDev** [comment]
@evstafev FYI - I got Electron 5.0.0.beta-* to build using electron-rebuild method. Of course, the gyp build method should also be made to work too.

**Comment by evstafev** [comment]
> @evstafev FYI - I got Electron 5.0.0.beta-* to build using electron-rebuild method. Of course, the gyp build method should also be made to work too.

@MikalDev node_modules\.bin\electron-rebuild -a ia32 -v 5.0.0-beta.1 -f -w greenworks
5.0.0-beta.1 - 5.0.0-beta.9
[errors.txt](https://github.com/greenheartgames/greenworks/files/3115487/errors.txt)

**Comment by evstafev** [comment]
Success rebuild with:

.\greenworks\src\api\steam_api_friends.cc:78
Fatal errors
```
- SET_TYPE(persona_change, "FacebookInfo", k_EPersonaChangeFacebookInfo);
+ //SET_TYPE(persona_change, "FacebookInfo", k_EPersonaChangeFacebookInfo);
```

.\greenworks\binding.gyp:177
Disable deprecation warnings
```
      'msvs_disabled_warnings': [
+		4996,
```

I will test the result

**Comment by evstafev** [comment]
`Error The specified procedure could not be found.`

**Comment by evstafev** [comment]
Crash app on linux, on windows all well

**Comment by evstafev** [comment]
**Need fix** please

**Comment by hokein** [comment]
The latest master should work now. I have test it on electron v5.0 on Mac.
