### ISSUE TITLE
Electron greenworks module could not be found.

### ISSUE THREAD

**Issue by KonScyence** [greenheartgames/greenworks#228]
I'm trying to use the library, but I find this error:
```
The specified module could not be found.
...\electron_folder\lib\greenworks-win64.node
```

I am currently using:
Greenworks v0.14.0
Electron v4.1.3

I saw that there was a lot of post on the subject, but I did not find the solution to my problem.

Here is all the files: https://github.com/KonScyence/launcher-911qc

Regards,
KonScyence

**Comment by MikalDev** [comment]
Some suggestions to debug:
- Are the steam dlls present in the same directory as the node file (they are not in your github repo, but you have them in your actual workspace.) I have seen this show up a module require error.
- To debug require paths, I also usually add this code before the require to understand where the module is running from and to make sure the relative path I am using in the require function is correct.

`                       // Check paths, but we'll use relative
                        console.log("*** INFO *** domSide.js, electron, require.resolve.paths(greenworks): " + require.resolve.paths('greenworks'));
                        // For debug, what is the DirName the current script is running in.
                        console.log("*** INFO *** domSide.js DirName: " + __dirname + " FileName: " + __filename);
`

A question, are you testing this by running the *.exe or using npm start or another method?

**Comment by KonScyence** [comment]
@MikalDev Actually, I only have the greenworks-win64.node file in lib, what other file am I supposed to have?

**Comment by MikalDev** [comment]
You need the steam works dlls from the steamworks SDK. I just made an electron quick start doc and added it the greenworks github (check the latest pull requests, since it has not been accepted yet.)

**Comment by KonScyence** [comment]
Now I have this error:
```
The module '...\node_modules\greenworks\lib\greenworks-win64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
```

What am I suppose to do?

Thanks for your help!

**Comment by connorsleight** [comment]
@MikalDev I think that electron quickstart guide is now outdated. I have the same issues as the OP but I have all of the right files according to quickstart
