### ISSUE TITLE
Request for Greenworks releases supporting NW.js v0.40.0+

### ISSUE THREAD

**Issue by TheRealDannyyy** [greenheartgames/greenworks#234]
First off, I'd like to **thank everyone** from _Greenheart Games_ for their amazing work! 
(Also thanks to any 3rd party contributions of course!)

I'm part of the _Construct Community_ and use both [Construct 2](https://www.scirra.com/construct2) and [Construct 3](https://www.construct.net/en) for HTML5 desktop game development. Based on the [releases page](https://github.com/greenheartgames/greenworks/releases), it's been quite a while since the last stable release. I'd really appreciate if we could get Greenworks support for the upcoming **v0.40.0** release of NWjs.

_Cheers!_

**Comment by NoSoul8** [comment]
upvoting from C3 user

**Comment by hokein** [comment]
Sounds reasonable to me. I'll make a new release in the near future.

**Comment by TheRealDannyyy** [comment]
Looks like the new major NW.js feature didn't make it into v0.40 yet. I would like to suggest to delay the next greenworks build until it's implemented (new window system). Will keep you posted if it's in.

Meanwhile I would really appreciate if [this PR](https://github.com/greenheartgames/greenworks/pull/220) could be approved for the next greenworks build.

**Comment by patrickklug** [comment]
Related: https://github.com/greenheartgames/greenworks/issues/239

**Comment by patrickklug** [comment]
@hokein any plans/timing on a new release yet (see above)?

**Comment by NoSoul8** [comment]
@hokein will the new release have "clear steam achievement" support?

**Comment by TheRealDannyyy** [comment]
Guys please don't hijack my issue and create your own.

**Comment by kaansoral** [comment]
I've been anxiously waiting for a release myself (Electron user here) - I've been using Electron 3 as Mac/Linux/Win combined, it was the most stable one with greenworks

At this point I really really want to switch to Electron 6, however, as I only have a robust dev environment in Mac, I can't really afford investing days into Linux/Windows builds, especially hard in Linux as working inside a virtual machine is a nightmare (game is dead slow inside a VM)

I don't know about NW.js, but it would be great if we could get a build for Electron, maybe the NW.js builds could be updated with another follow-up release

**Comment by Armaldio** [comment]
Hello @kaansoral 

I'm providing regular (daily) and automated builds for greenworks (mac, linux, windows, x64, x86)

Here is the repository with the greenworks releases: [repo](https://github.com/ElectronForConstruct/greenworks-prebuilds), [releases](https://github.com/ElectronForConstruct/greenworks-prebuilds/releases)
Here is an utility website (beta) to download (, filter, etc..) them: https://greenworks-prebuilds.armaldio.xyz/?runtime=electron ([repo](https://github.com/ElectronForConstruct/greenworks-prebuilds-website))

Each release is built against an [abi](https://nodejs.org/uk/docs/guides/abi-stability/), so to know which abi correspond to which version, use the [modules-abi](https://github.com/armaldio/modules-abi) package:

```sh
$ npx modules-abi --mode=abi --target=5.0.1 --runtime=electron
```
> return the abi corresponding to electron v5.0.1

**Comment by kaansoral** [comment]
Thank you @Armaldio - you're a saviour, can't wait to try them out :)

**Comment by TheRealDannyyy** [comment]
@hokein NW2 has been released. I'd really appreciate if you could push new builds with the following:
- Support for latest NW.js release
- Update to Steamworks SDK v1.46
- Merge pull request #220 

_Cheers!_

**Comment by prominentdetail** [comment]
@TheRealDannyyy is the v79 files on https://github.com/ElectronForConstruct/greenworks-prebuilds/releases for (0.43.0-beta10.43.4) ?
because it shows the versions on this page: https://greenworks-prebuilds.armaldio.xyz/ provided by @Armaldio 
Maybe we can utilize these? Or am I misunderstanding?

**Comment by TheRealDannyyy** [comment]
It should work with the version range mentioned on the website. It however doesn't include any of the open PR's.

**Comment by prominentdetail** [comment]
@TheRealDannyyy Ok thanks, and I assume it only works with the older Steam SDK v1.42 ? 
@Armaldio

**Comment by TheRealDannyyy** [comment]
It supports the version mentioned in this repo.

**Comment by patrickklug** [comment]
> Hello @kaansoral
> 
> I'm providing regular (daily) and automated builds for greenworks (mac, linux, windows, x64, x86)
> 
> Here is the repository with the greenworks releases: [repo](https://github.com/ElectronForConstruct/greenworks-prebuilds), [releases](https://github.com/ElectronForConstruct/greenworks-prebuilds/releases)
> Here is an utility website (beta) to download (, filter, etc..) them: https://greenworks-prebuilds.armaldio.xyz/?runtime=electron ([repo](https://github.com/ElectronForConstruct/greenworks-prebuilds-website))
> 
> Each release is built against an [abi](https://nodejs.org/uk/docs/guides/abi-stability/), so to know which abi correspond to which version, use the [modules-abi](https://github.com/armaldio/modules-abi) package:
> 
> ```shell
> $ npx modules-abi --mode=abi --target=5.0.1 --runtime=electron
> ```
> 
> > return the abi corresponding to electron v5.0.1

@Armaldio Great resource! I wanted to add this link to the official README but noticed the last available build was from 02/13/2020 - Could you confirm that the site is still operational?

**Comment by Armaldio** [comment]
Hello,

Yes, the website is still working, I just forgot to publish the latest version ^^
There is a cron that build  it every day

**Comment by patrickklug** [comment]
@Armaldio thanks so much for this. I've added a link on the main readme page to make this easier to find for folks.

**Comment by Maelfyn** [comment]
Wow! Thank you for this! Imho, show that filter menu on the website by default. It's very useful!

**Comment by Maelfyn** [comment]
That website does, indeed, have the latest versions of the greenworks-win64.node file, but it doesn't have the accompanying greenworks.js file. Don't you need both in order to run them together? Do updated files of greenworks.js exist?

**Comment by TheRealDannyyy** [comment]
I think since we now offer prebuild binaries outselves, the initial issue has been solved. We'll probably be getting the downloader website out of beta soon as well. 

For anyone finding this closed issue at some point in the future:
- Prebuild Downloader Website: https://greenworks-prebuilds.armaldio.xyz/
- Construct Engine Help: https://www.construct.net/en/forum/construct-3/general-discussion-7/up-to-date-greenworks-support-148250

**Comment by prominentdetail** [comment]
@Armaldio can we get one for 0.46.0 that was just released?

**Comment by Armaldio** [comment]
@prominentdetail Please open your own issue!
I just looked at the logs, buoldi'g this specific version does not show any errors but it's not on the website nor the release page indeed. Will look into it

**Comment by PneumaTim** [comment]
So as I javascript programmer and very little else (read: nothing else) I'm struggling to work out which greenworks node version works with which nw.js version; the abi thing (which I don't understand) apparently doesn't work for nw.js anyway, even if I did understand it. Just to throw it out there on the off chance someone nice can help me before my game launches tomorrow (yes this is a last-ditch attempt) - I'm using nw.js version 0.47.2 for Windows and 0.31.5 for Mac, are either of those compatible with any of the latest greenworks versions?

Long shot and I appreciate anyone helping - there's a free Steam key in it!!! As if anyone would want one...

**Comment by Armaldio** [comment]
@PneumaTim For NW.js version 0.47.2, abi v84 should work
https://greenworks-prebuilds.armaldio.xyz?runtime=nw.js&version=84&tag=null

If you hover over the version you can et the range of version the abi support
![image](https://user-images.githubusercontent.com/3089715/99532378-7b9a0980-29a4-11eb-87a4-72b00919e884.png)

Unfortunately I don't provide builds for 0.31.5. The last one we have is abi 70 (0.34.0 → 0.34.5)

**Comment by PneumaTim** [comment]
I feel like an idiot. Not because I didn't realise this, just generally...

Thanks Armaldio!!  Very much appreciated!
