### ISSUE TITLE
The specified procedure could not be found

### ISSUE THREAD

**Issue by dimielannes** [greenheartgames/greenworks#247]
I am doing a test project (Scirra/Construct 3) to configure the Greenwork plugin, I exported using the settings:

NW.js version: 0.30.4
NW.js architecture: x64
Node.js version: v10.1.0.
Steam SDK 1.42

Projects files attached

![html](https://user-images.githubusercontent.com/8438162/65471327-21a3bf80-de45-11e9-8777-a95a6fa85739.png)
![files](https://user-images.githubusercontent.com/8438162/65471431-73e4e080-de45-11e9-9db8-766e2f9c6b1e.png)
![erro](https://user-images.githubusercontent.com/8438162/65471446-83642980-de45-11e9-85ee-563a73f36017.png)

**Comment by dimielannes** [comment]
Update to NW.js: 0.33.3 and works fine!!!

**Comment by Josh1billion** [comment]
I ran into this exact error over the weekend.  Fixed it by upgrading to a newer version of the Steamworks SDK.  Or specifically, using newer versions of the DLLs in Steamworks.

The DLLs that came with the old Steamworks SDK I was using (from 2016) must have been lacking a procedure Greenworks uses now.

**Comment by Usnul** [comment]
specifically for me version 146 of SDK worked around that time (README as of right now recommends version 142, which will fail)
