### ISSUE TITLE
SteamUser()->GetAuthSessionTicket() for user authentication

### ISSUE THREAD

**Issue by MarxGames** [greenheartgames/greenworks#25]
https://partner.steamgames.com/documentation/auth#client_to_backend_webapi

**Comment by bgSosh** [comment]
+1

**Comment by jahrain** [comment]
Implemented on my fork: https://github.com/jahrain/greenworks

 PR here: https://github.com/greenheartgames/greenworks/pull/37

**Comment by bgSosh** [comment]
Note that this approach is not reliable though.  We've done the same thing ourselves and are seeing some failures (<5%, but significant), where the auth ticket is an empty string.  From steam docs:

> To guarantee a valid ticket, the client must wait for the GetAuthSessionTicketResponse_t callback

Does anyone know how to register a callback like this with greenworks?

**Comment by bgSosh** [comment]
(Apologies - my comment was based on old code. Removed)

**Comment by hokein** [comment]
Close it since it has been supported in #37.
