### ISSUE TITLE
Error compiling on electron-rebuild

### ISSUE THREAD

**Issue by KonScyence** [greenheartgames/greenworks#251]
Hi, trying to build greenwork on this spec:
Electron: v. 7.1.1
Node.JS: 10.15.3
npm: 6.12.0
steamworks: 1.46

Here is the full error: https://pastebin.com/FuNU9AgP

**Comment by MikalDev** [comment]
I have not yet read of anyone getting Steamworks SDK 1.46 to build. The release is using 1.42. Perhaps that is an issue?

If you can use a *.node version built with the 1.42 SDK, check out this prebuild *.node website (in beta): https://greenworks-prebuilds.armaldio.xyz/ (use the side menu to select Electron builds).

I have used it successfully with Electron 7.x.

Note, one thing I had to do to a different way to require greenworks.js on 7.x (which I did not have to do before 7.x was to require it with this method.) This may be a result/config of my specific Electron build which uses Electron For Construct and Construct 3 (it looks like sandboxing is enabled.)

Change:
require('../../app.asar.unpacked/greenworks/greenworks'); to require('electron').remote.require('../app.asar.unpacked/greenworks/greenworks');

**Comment by KonScyence** [comment]
Thank you for your help. I tried, 1.45 1.44 1.43, but only 1.42 seem to work. For them searching the link to download the steamworks 1.42, there you will find all versions: https://partner.steamgames.com/downloads/list.
