### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by Jaffa-Cakes** [greenheartgames/greenworks#253]
I see there has not been a release since 2018 targeting v4.0.0 of Electron, is this repo still maintained?

**Comment by hokein** [comment]
This is still maintained though we don't have active development nowadays. I don't have band width to make a new release, there are two options to use greenwork with the latest electron:
- try to build the binary for source code
- or use the prebuilt binary from https://greenworks-prebuilds.armaldio.xyz/
