### ISSUE TITLE
Greenworks module cannot be found, but file is in the correct location

### ISSUE THREAD

**Issue by gritfish** [greenheartgames/greenworks#26]
Using both these methods:
http://html5hub.com/deploying-hybrid-html5-games-on-the-desktop-using-node-webkit/
https://github.com/mllrsohn/grunt-node-webkit-builder/

Node-webkit reports the following error:
Uncaught Error: The specified module could not be found.
C:\Users\<username>\AppData\Local\Temp\nw10964_10616\lib\greenworks-win64.node

and these lines from the sample code don't work:
var greenworks = require('./greenworks');
document.write(greenworks.initAPI());

However copying that file location into windows explorer shows that the file exists. I'm not sure what this means.

**Comment by hokein** [comment]
@gritfish 
Does it work before you create the app.nw package?

**Comment by gritfish** [comment]
Dragging the index.html file into a new node-webkit (nw.exe) window gets up to "Error on initializing steam API."
following the zip->rename to .nw->copy+bundle process and then opening gets the module could not be found issue.
I don't know if it helps but this is what my files look like - they're all just the greenworks test files (with greenworks.js moved into the folder)
![files](https://cloud.githubusercontent.com/assets/1240407/8267543/8f3d397a-17a9-11e5-9089-d72f417ed952.png)

**Comment by hokein** [comment]
Looks like you forget to copy `steam_api.dll` to `nw.js/lib` directory.

**Comment by gritfish** [comment]
That file was there, but it wasn't shown in sublimetext's sidebar :(
But I just copied the ENTIRE contents of the /redistributable_bin/ folder in the /lib directory and it works perfectly now

Thanks for all the help!

**Comment by peterbaricic** [comment]
I have this same issue, copying contents of the /redistributable_bin/ doesn't help. I'm testing this with the sample app. This error shows only on windows, mac version works. I use web2executable to compile it with nwjs version 0.12.1.
![greenworks1](https://cloud.githubusercontent.com/assets/6643903/11063044/1fdecfbe-87b4-11e5-9318-b5c219480dd3.png)
![greenworks2](https://cloud.githubusercontent.com/assets/6643903/11063045/200933d0-87b4-11e5-9552-29e11c9d1753.png)

**Comment by MarxGames** [comment]
@peterbaricic Make sure your executables are named nw instead of your app name.

**Comment by Raicuparta** [comment]
If you want to rename the exectuable, use [RenameImportDLL](http://developers.ironsrc.com/rename-import-dll/)

**Comment by peterbaricic** [comment]
thanks, that helped

**Comment by twinmatrix** [comment]
I have the same problem. I'm using RPG Maker MV's internal NW build that creates a Game.exe. I copied ALL Steam SDK files and renamed Game.exe into nw.exe but it doesn't help.

![image](https://cloud.githubusercontent.com/assets/15997983/11365394/65edc8dc-92a6-11e5-971d-1a248f39ace0.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365398/6c803e78-92a6-11e5-9b47-61ad58b25105.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365399/7137ec22-92a6-11e5-88cd-9ae9ba5735f9.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365402/774cb836-92a6-11e5-8f01-edc7fdc910f2.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365403/7dd60d74-92a6-11e5-9541-62a2d58fbd8e.png)

**Comment by chuuu** [comment]
@twinmatrix Exactly the same problem here!!!  I'm also using RMMV.  I've been searching desparately for more than 3 days but still couldn't find a solution to this.

Did you find a workaround in the end?

**Comment by marcgfx** [comment]
I was getting the same error. I had to rebuild greenworks for my target and the problem went away. Did not find any information on this online, I was just lucky it worked.

nw-gyp configure --target=0.28.2
nw-gyp build --target=0.28.2

**Comment by hokein** [comment]
@marcgfx We don't provide the greenwork prebuilt binary for nw.js v0.28 yet. I believe it was caused by using an incompatible greeenworks binary on nw.js.

**Comment by marcgfx** [comment]
@hokein I was not using the prebuilt binaries. I built them myself but without specifying a target. I just thought it might be good to know, that this can also be a cause of the error. We are in agreement :)
