### ISSUE TITLE
greenworks.init tries to find steam_appId at OS root on Mac

### ISSUE THREAD

**Issue by skymen** [greenheartgames/greenworks#260]
Hi,
I'm trying to package a steam game for MacOS. On Windows everything works fine, but on Mac, it seems like this don't really work the way they should.

```JS
greenworks.init = function() {
  if (this.initAPI()) return true;
  if (!this.isSteamRunning())
    throw new Error("Steam initialization failed. Steam is not running.");
  var appId;
  try {
    appId = fs.readFileSync('steam_appid.txt', 'utf8');
  } catch (e) {
    throw new Error("Steam initialization failed. Steam is running," +
                    "but steam_appid.txt is missing. Expected to find it in: " +
                    require('path').resolve('steam_appid.txt'));
  }
  if (!/^\d+ *\r?\n?$/.test(appId)) {
    throw new Error("Steam initialization failed. " +
                    "steam_appid.txt appears to be invalid; " +
                    "it should contain a numeric ID: " + appId);
  }
  throw new Error("Steam initialization failed, but Steam is running, " +
                  "and steam_appid.txt is present and valid." +
                  "Maybe that's not really YOUR app ID? " + appId.trim());
}
```
First of all, this code will always throw an error, unless this.initAPI() returns true.
And on Mac there are 2 other issues.
If initAPI returns false, it tries to find steam_appid.txt at `/steam_appid.txt` instead of `./steam_appid.txt`
So the game fails to launch if I don't have steam_appid.txt at the root of my OS.

What's even weirder, is that if I patch the code to instead use __dirname:
```JS
greenworks.init = function() {
  if (this.initAPI()) return true;
  if (!this.isSteamRunning())
    throw new Error("Steam initialization failed. Steam is not running.");
  var appId;
  try {
    let appIdPath = require('path').resolve(__dirname, 'steam_appid.txt');
    console.log(appIdPath)
    appId = fs.readFileSync(appIdPath, 'utf8');
  } catch (e) {
    throw new Error("Steam initialization failed. Steam is running," +
                    "but steam_appid.txt is missing. Expected to find it in: " +
                    require('path').resolve(__dirname, 'steam_appid.txt'));
  }
  if (!/^\d+ *\r?\n?$/.test(appId)) {
    throw new Error("Steam initialization failed. " +
                    "steam_appid.txt appears to be invalid; " +
                    "it should contain a numeric ID: " + appId);
  }
  throw new Error("Steam initialization failed, but Steam is running, " +
                  "and steam_appid.txt is present and valid." +
                  "Maybe that's not really YOUR app ID? " + appId.trim());
}
```
The function still throws an error since all branches lead to a throw.

I suppose the code was designed to call initAPI and if it fails try to figure out why it did.
So the issue is also in initAPI because even with my patched code, it still tries to read steam_appid.txt at the root of my OS, and will fail if the file isn't there.

**Comment by skymen** [comment]
Ok, I found this issue: https://github.com/greenheartgames/greenworks/issues/183
It vaguely guided me towards the right direction.

When trying to launch the app from the .app file, it failed to work.
If instead, I launched the executable located at
`<appName>.app/Content/MacOS/<appName`
it tried to find steam_appid.txt at the home folder.
If I tried launching from a terminal instead, with the terminal opened at
`<appName>.app/Content/MacOS/<appName`
it tried finding steam_appid.txt next to the executable file
the solution was to instead open the terminal in the folder where <appName>.app is and launch `<appName>.app/Content/MacOS/<appName` from the terminal.

Hope this will help anyone who has the same issue

**Comment by dschibait** [comment]
Hi,
just reaching this thread (found it during my research with same /steam_appid problem)

For me this was a problem with signing. When opening the 
<appName>.app/Content/MacOS/<appName
you can review the errors and for me it says that the steamclient.dylib can't be loaded cause of a signing (Team id) problem.

I had a sucessful project on steam, and with a newer version of electron-osx-sign it appears that this signing problem take place - im not a 100% sure, but i think it was caused by default entitlements set from the tool. With an old version the signing works and also this error disappeared. (i have to try to -fix- the newer version next weeks)

I didn't investigate why the tool tries to load it from "/" - with fixing the above signing problem it works, without changing directory or something, just open the App.app file.

hope this helps someone :) to get pushed in a possible direction
