### ISSUE TITLE
Electron v9 with Webpack?

### ISSUE THREAD

**Issue by DnOberon** [greenheartgames/greenworks#268]
Has anyone gotten this up and running on Electron v9? I'm attempting to do so, but am running into an issue. Everything builds just fine (Steamworks sdk 1.42 and latest prebuild for electron, app built with vue-cli) but when attempting to run the electron app I get faced with this error.

```
These relative modules were not found:
* ./lib/greenworks-linux32 in ./node_modules/greenworks/greenworks.js
* ./lib/greenworks-linux64 in ./node_modules/greenworks/greenworks.js
* ./lib/greenworks-osx64 in ./node_modules/greenworks/greenworks.js
* ./lib/greenworks-win32 in ./node_modules/greenworks/greenworks.js
* ./lib/greenworks-win64 in ./node_modules/greenworks/greenworks.js
```
I'm not sure what's going on, but I get the feeling it might be related to webpack and not the greenworks itself. Any tips would be greatly appreciated.

**Comment by enchantinggg4** [comment]
@DnOberon did you manage to make it work? I am on electron 8 and getting `Module not found: Error: Can't resolve './lib/greenworks-osx32' in '/Users/itachi/WebstormProjects/d2c-app/node_modules/greenworks'`

**Comment by DnOberon** [comment]
@enchantinggg4 I rethought my life choices and started using Unity to build the game I was working on instead. So effectively, I gave up and found no solution :P
