### ISSUE TITLE
SteamUserStats()->ResetAllStats()

### ISSUE THREAD

**Issue by morgondag** [greenheartgames/greenworks#27]
Just wondering if you have implemented reset achievements?
like ```SteamUserStats()->ResetAllStats()```

Or if its available some how though greenworks?
Its a convenient way in development to reset and test achievements triggers.

**Comment by hokein** [comment]
I have impemented some APIs to manipulate Steam achievements, will be available in next release.
You can use those API to reset all your achievements via 

```
var achievements = greenworks.getAchievementNames();
for (var i = 0; i < achievements.length; ++i) {
   greenworks.clearAchievement(achievements[i], success_callback, error_callback);
}
```

I will merged this issue into #23 .
