### ISSUE TITLE
Error build with the new version of Greenworks

### ISSUE THREAD

**Issue by mxslam** [greenheartgames/greenworks#278]
Hi i got a error when i try to build greenworks with electron rebuild, it's happening just with the new update of greenworks, but it work with a old version (march 2020 is working), here the error log with the newest version of greenworks : [erreurcomplete-1.txt](https://github.com/greenheartgames/greenworks/files/5431146/erreurcomplete-1.txt) 

Thanks.

**Comment by hokein** [comment]
`NewUrlLaunchParameters_t` is introduced in steamworks v1.43. Looks like you are using an old version, please download the latest version of steamworks SDK, and recompile the project.
