### ISSUE TITLE
Please clarify point in documentation

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#29]
Please could you clarify `greenworks binaries directory` and `code directory` in the docs?  It wasn't clear to me which these were.

> Copy steam_api.dll/libsteam_api.dylib/libsteam_api.so library from the Steamworks SDK(<steam_sdk_path>/redistributable_bin/) to greenworks binaries directory.

> Create a steam_appid.txt file with your Steam APP ID under code directory.

**Comment by hokein** [comment]
I have updated the doc.
* The `greenworks binaries directory` is the dir where you put the greenworks node addon(greenwork-*.node).
* The `code directory` is your application dir.

The [start-greenworks-in-nwjs](https://github.com/greenheartgames/greenworks#start-greenworks-in-nwjs) section provides a more detailed usage, you can refer to that.

**Comment by bgSosh** [comment]
Thank you!
