### ISSUE TITLE
greenworks.getSteamId() opens steamOverlay

### ISSUE THREAD

**Issue by Baccanno** [greenheartgames/greenworks#31]
when I do greenworks.getSteamId() to retrieve the steam user info the steam overlay activates itself on its own.

This is not at all the expected behaviour :) 

greenworks 0.4.1 sdk 1.34

**Comment by ReflextionsDev** [comment]
Also have the same issue, it's pretty crippling to the project :(

**Comment by Baccanno** [comment]
Hi, I recompiled greenworks with nw-gyp configure --target=0.12.3 and sdk134 the issue seems to have evaporate!
