### ISSUE TITLE
Will you consider adding an API for "ShowFloatingGamepadTextInput" in the future?

### ISSUE THREAD

**Issue by mmmm748748** [greenheartgames/greenworks#327]
That.. Will you consider adding an API for "[ShowFloatingGamepadTextInput](https://partner.steamgames.com/doc/api/ISteamUtils#ShowFloatingGamepadTextInput)" in the future?
Because I would like to be able to call up the virtual keyboard on the Steam Deck...

**(by Claude Translate🙇‍♀️)**

**Comment by hokein** [comment]
It should not be hard to support this API (and the `FloatingGamepadTextInputDismissed_t ` event).

**Comment by TheMalcs** [comment]
I would also like this implemented, it would make Steam Deck compatibility just a bit more convenient for us and our players.

**Comment by hokein** [comment]
I have limited free time, but I will try to add support for it in the next release.

**Comment by TheMalcs** [comment]
> I have limited free time, but I will try to add support for it in the next release.

It's no worries at all, take your time! We appreciate the recent support of this as its helped greatly with development. It's already in very usable state, and these are only "nice to haves" :)
