### ISSUE TITLE
ShowFloatingGamepadTextInput incorrectly checks if the 5th arg is a String instead of an Int32, resulting in a "bad arguments" error when attempting to call.

### ISSUE THREAD

**Issue by MelvorIdle** [greenheartgames/greenworks#333]
Thank you for the implementation of this API.

Unfortunately, ShowFloatingGamepadTextInput incorrectly checks if the 5th arg is a String instead of an Int32, resulting in a "bad arguments" error when attempting to call.

Code in question:
`src/api/steam_api_utils.cc`
```c++
NAN_METHOD(ShowFloatingGamepadTextInput) {
  Nan::HandleScope scope;
  if (info.Length() < 5 || !info[0]->IsInt32() || !info[1]->IsInt32() ||
      !info[2]->IsInt32() || !info[3]->IsInt32() || !info[4]->IsString()) {
    THROW_BAD_ARGS("Bad arguments");
  }
```

I believe `!info[4]->IsString())` should instead be `!info[4]->IsInt32())`

**Comment by hokein** [comment]
Good catch, thanks!
