### ISSUE TITLE
Greenworks Prebuild website not providing daily builds for NW.js versions 0.88.0 -> 0.93.0

### ISSUE THREAD

**Issue by TheMalcs** [greenheartgames/greenworks#334]
The prebuild website seems to not be providing daily automated builds for W.js versions 0.88.0 -> 0.93.0. The last updated build was 20 days ago. It seems to be working fine for Node JS and Electron.

I'd like to use the latest fix for ShowFloatingGamepadTextInput in our project (but always run into issues building for NW.js on our end).

Thanks!

**Comment by hokein** [comment]
The prebuild website is maintained separately, and I don’t know much about it. 

I'll be releasing a new version for NW.js in the coming December.
