### ISSUE TITLE
greenworks_async_workers.cc compilation errors

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#35]
Hi,

I'm trying to compile the latest version in the repo (greenworks-master), but am getting some compilation errors in greenworks_async_workers.cc (I can compile the 0.4.1 release without problems). 

        ..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ')' before '{' [xxx\greenworks-master\build\greenworks-win32.vcxproj]
        ..\src\greenworks_async_workers.cc(192): error C2059: syntax error : ')' [xxx\greenworks-master\build\greenworks-win32.vcxproj]
        ..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ';' before '{' [xxx\greenworks-master\build\greenworks-win32.vcxproj]

Seems to be caused by this change:

https://github.com/greenheartgames/greenworks/commit/71b5219b38505a3df8a12b9b48e7ad200e91b3c1

       void ClearAchievementWorker::HandleOKCallback() {
         NanScope();
      -  v8::Local<v8::Value> argv[] = { NanNew(success_) };
      -  callback->Call(1, argv);
      +  callback->Call(0, {});
       }

**Comment by hokein** [comment]
You are required to build it in VS 2013. 

Someone has meet this error before, I think it's resonable to remove such code usage to enable build on VS2012.

**Comment by bgSosh** [comment]
Building in gyp on windows is so fragile that I don't want to change the VS environment in case something breaks.
