### ISSUE TITLE
provide a release for nwjs 0.13.xx,

### ISSUE THREAD

**Issue by patrickklug** [greenheartgames/greenworks#42]

**Comment by hokein** [comment]
@patrickklug 
The nwjs 0.13.xx is still under heavy development, and it seems quite unstable. We need to wait until it become more stable and release stable version before we release a greenworks for 0.13.

Currently, I sugguest that we make a release for nwjs v0.12.1(The lastest overlay-worked version of nw.js) with new steam sdk version.
