### ISSUE TITLE
Possible to build greenworks against electron on windows?

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#55]
Is it possible to build greenworks against electron on windows?  These instructions appear to be linux only:

`HOME=~/.electron-gyp node-gyp rebuild --target=<0.29.2 or other versions> --arch=x64 --dist-url=https://atom.io/download/atom-shell`

**Comment by hokein** [comment]
Yes, it supports build electron version on Windows. The command should work on a linux-like terminal, e.g. cgwin.

**Comment by hokein** [comment]
I'm closing this as atom/electron#3253 has been give a solution for it.

**Comment by bgSosh** [comment]
Thank you
