### ISSUE TITLE
Problems compiling against electron on windows

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#56]
I'm getting many errors when trying to compile greenworks for electron.  I'm trying v0.34.1, but have tried older versions back to 0.29, and get the same problem.  I've been able to compile greenworks against nwjs without problems on this machine, so not really sure what's wrong. 

The commands I'm using are:

     set HOME=C:\Dev\.electron-gyp
     node-gyp rebuild --target=0.34.1 --arch=ia32 --dist-url=https://atom.io/download/atom-shell 

The initial errors are (followed by a few hundred more):

     C:\Dev\.electron-gyp \.node-gyp\0.34.1\deps\v8\include\v8.h(336): error C2988: unrecognizable template declaration/definition (..\src\greenworks_utils.cc) [C:\xxx\greenworks\build\greenworks-win32.vcxproj]
     C:\Dev\.electron-gyp \.node-gyp\0.34.1\deps\v8\include\v8.h(336): error C2059: syntax error : 'using' (..\src\greenworks_utils.cc) [C:\xxx\greenworks\build\greenworks-win32.vcxproj]
     C:\Dev\.electron-gyp \.node-gyp\0.34.1\deps\v8\include\v8.h(469): error C2988: unrecognizable template declaration/definition (..\src\greenworks_utils.cc) [C:\xxx\greenworks\build\greenworks-win32.vcxproj]
     C:\Dev\.electron-gyp \.node-gyp\0.34.1\deps\v8\include\v8.h(469): error C2059: syntax error : 'using' (..\src\greenworks_utils.cc) [C:\xxx\greenworks\build\greenworks-win32.vcxproj]
     C:\Dev\.electron-gyp \.node-gyp\0.34.1\deps\v8\include\v8.h(576): error C2061: syntax error : identifier 'WeakCallbackType' (..\src\greenworks_utils.cc) [C:\xxx\greenworks\build\greenworks-win32.vcxproj]
     C:\Dev\.electron-gyp \.node-gyp\0.34.1\deps\v8\include\v8.h(642) : see reference to class template instantiation 'v8::PersistentBase<T>' being compiled

**Comment by hokein** [comment]
Have you updated all the `node_modules` under  `<greenworks-src>/` directory via `npm install`?
And which version of VS are you using?

**Comment by bgSosh** [comment]
Yes, dependencies installed with `npm install

**Comment by hokein** [comment]
@bgSosh I think you need to upgrade to VS 2013 Update 4 since electron are required VS 2013 Update 4  to build.

**Comment by bgSosh** [comment]
Ok, so I've created a fresh install of Win7 in a VM, with VS 2013 Update5 (Update 4 does not seem to be available).  However, now I can't `npm install` the greenworks dependencies.

On the fresh Windows, I have installed:
- VS 2013 Update 5
- Python 2.7.10
- Node 4.2.1 (LTS)
- Greenworks 5.1
- Steamworks sdk 1.35 (in greenworks/deps/steamworks_sdk)

The error I'm getting, when I try to `npm install` is:

     Creating library C:\dev\greenworks-0.5.1\build\Release\greenworks-win32.lib and object                C:\dev\greenworks-0.5.1\build\Release\greenworks-win32.exp
     minizip.lib(unzip.obj) : error LNK2001: unresolved external symbol _crc32 [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(unzip.obj) : error LNK2001: unresolved external symbol _inflateInit2_ [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(unzip.obj) : error LNK2001: unresolved external symbol _inflate [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(unzip.obj) : error LNK2001: unresolved external symbol _inflateEnd[C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(zip.obj) : error LNK2001: unresolved external symbol _deflateEnd [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(zip.obj) : error LNK2001: unresolved external symbol _deflate [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(zip.obj) : error LNK2001: unresolved external symbol _deflateInit2_ [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     minizip.lib(zip.obj) : error LNK2001: unresolved external symbol _get_crc_table [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]
     C:\dev\greenworks-0.5.1\build\Release\greenworks-win32.node : fatal error LNK1120: 8 unresolved externals [C:\dev\greenworks-0.5.1\build\greenworks-win32.vcxproj]

Any idea what's wrong?

**Comment by hokein** [comment]
@bgSosh It should be fixed now. Please test it with lastest master branch.

**Comment by bgSosh** [comment]
@hokein - `npm install` is working now.  Thank you very much!
