### ISSUE TITLE
Triggering SteamAPI_RunCallbacks()

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#59]
Hi,

I'm trying to add support to trigger SteamAPI_RunCallbacks().  I had this working with a custom version of greenworks 4 and NWJS, but I'm having trouble with greenworks 5 and electron (I'm not yet sure if it's an electron compatibility issue, or whether I'm doing something wrong with the new NAN syntax)

I'd like to ask for a sanity check of this code....

I'm defining a function to call the steam api like this (in greenworks_api.cc) : 

     NAN_METHOD(RunSteamApiCallbacks) {
       Nan::HandleScope scope;
       SteamAPI_RunCallbacks();
       info.GetReturnValue().Set(Nan::Undefined());
     }

And exposing it like this:

       Nan::Set(target,
    	   Nan::New("RunSteamApiCallbacks").ToLocalChecked(),
           Nan::New<v8::FunctionTemplate>(RunSteamApiCallbacks)->GetFunction());

However, if I call this from the JS while the overlay is open (in electron & windows), then either the application hangs or crashes.

Can you see any problems with the code?  Or have any ideas what else might be going wrong?

Thank you

**Comment by hokein** [comment]
That's weird. The code looks fine to me.

> However, if I call this from the JS while the overlay is open (in electron & windows), then either the application hangs or crashes.

Does the crash or hangs happen when the overlay doesn't open? Aslo Can you get the crash stack and paste it here?

BTW, The Greenworks v5 has [integrated](https://github.com/greenheartgames/greenworks/blob/master/src/steam_client.cc#L94) with `SteamAPI_RunCallbacks` by calling it every 100ms. So I think you don't need to expose it in JS.

**Comment by bgSosh** [comment]
> That's weird. The code looks fine to me.

Ok. Thanks for checking.

> Does the crash or hangs happen when the overlay doesn't open? 

With the overlay closed SteamAPI_RunCallbacks() happens without issue.  When run callbacks happens with the overlay open then it either freezes the app (if I call greenworks in the electron BrowserWindow or preload JS) or crashes (if I call greenworks from the electron main.js process).

> Aslo Can you get the crash stack and paste it here?

I don't see a crash stack - the electono app just closes in the case of this crash. (Unless there are crash reports logged somewhere?)

> BTW, The Greenworks v5 has integrated with SteamAPI_RunCallbacks by calling it every 100ms. So I think you don't need to expose it in JS.

Interesting!  There's no need for me to call it manually in that case.  Now I need to investigate why some other of my code wasn't triggered by the 100ms callbacks :)

**Comment by bgSosh** [comment]
So i've stopped calling the `SteamAPI_RunCallbacks()` manually and am now relying on the greenworks 100ms call.   However, the MicroTxnAuthorizationListener that we added does not seem to be called when a user authorizes a transaction.   (This was working previously in our custom greenworks 4.1 with NWJS, but we had to abandon NWJS due to memory leaks.).  

So now I'm trying to figure out what link in the chain is failing.   The three most likely causes seem to be:
 - I've done something wrong in the `MicroTxnAuthorizationListener` code, with the NAN update.
 - Something consuming the event, so it's not triggered in our code.
 - SteamAPI_RunCallbacks() not actually being called maybe? (Any way to verify the 100ms call?)
 - Some obscure compatibility issue with electron (I hope not!)

I've added our `MicroTxnAuthorizationListener` code to a gist snippet (below). @hokein if you have time, would you be able to give it a quick check please? It would be much appreciated, and we will happily contribute it once it's working properly!

https://gist.github.com/bgSosh/ed8bfe090421822042ba

**Comment by hokein** [comment]
@bgSosh 
I'm not sure the root cause just reading your code. But I can advise you to use another implementation which should work:
Move the `OnMicroTxnAuthorizationResponse` implementation to `SteamClient`, you can reference `OnGameOverlayActivated` for details. So the final API will like:`greenwork.on('micro-txn-authorization-response', function(orderId, authorized))`.

**Comment by bgSosh** [comment]
@hokein Thank you, I'll give that a try.

**Comment by bgSosh** [comment]
@hokein Hmm, I don't seem to be able to use the event emmiter.  I'm getting `TypeError: greenworks.on is not a function`, when I try to add this event handling code  (after greenworks has returned true for `initAPI()`,  and without any modifications to `steam_client.cc`  )

	greenworks.on('game-overlay-activated', function(is_active) {
		alert('game overlay is activated? '  + is_active);
	});

**Comment by hokein** [comment]
Do you use the latest master build? You need to include greenworks module via `greenworks.js` file instead of requiring the native module directly. The implementation of event emitter relies on [it](https://github.com/greenheartgames/greenworks/blob/master/greenworks.js#L99-L101).

**Comment by bgSosh** [comment]
> Do you use the latest master build?

We're using the 0.5.1 release source, rather than master.

> You need to include greenworks module via greenworks.js file instead of requiring the native module directly. The implementation of event emitter relies on it.

Ah I see, thanks - we weren't using that. I'll look at integrating that event emitter code.

**Comment by bgSosh** [comment]
This is not throwing an error anymore, but the function is not being triggered, when overlay is opened or closed.  I'm going to try compiling the non-modified master source, to see if that helps.

     greenworks.on('game-overlay-activated', function(is_active) {
         alert('game overlay is activated? '  + is_active);
     });

**Comment by bgSosh** [comment]
I set up the electron sample project, and verified that the greenworks event emitter was working.  I then reduced our project down to the bare minimum, but still could not get the greenworks events to fire.  After trial and error, I discovered something odd:  For the events to fire, you first need to call a random function from the api (any function, it seems) e.g. greenworks.getNumberOfPlayers().   The events will not fire unless you call something first (I'm calling initAPI() in all cases of course).

@hokein: this looks like a bug - are you able to reproduce?  Easiest way to check is to comment out these lines in the electron sample main.js:

      greenworks.saveTextToFile('test_file.txt', 'test_content',
          function() { log('Save text to file successfully'); },
          function(err) { log('Failed on saving text to file'); });

      greenworks.readTextFromFile('test_file.txt', function(message) {
          log('Read text from file successfully.'); }, function(err) {
          log('Failed on reading text from file'); });

      greenworks.getCloudQuota(
          function() { log('Getting cloud quota successfully.') },
          function(err) { log('Failed on getting cloud quota.') });

      greenworks.activateAchievement('achievement',
          function() { log('Activating achievement successfully'); },
          function(err) { log('Failed on activating achievement.'); });

      greenworks.getNumberOfPlayers(
          function(a) { log("Number of players " + a) },
          function(err) { log ('Failed on getting number of players'); });

**Comment by bgSosh** [comment]
I've opened a new issue describing the possible bug:

https://github.com/greenheartgames/greenworks/issues/61

Closing this now.  Will try to submit OnMicroTxnAuthorizationResponse code soon.
