### ISSUE TITLE
EventEmitter events not firing, unless some api function called first.

### ISSUE THREAD

**Issue by bgSosh** [greenheartgames/greenworks#61]
I think I've found a bug with the EventEmitter code.  This was with electron 31.2 though, so could be an electron compatibility issue.

I set up the electron sample project, and verified that the greenworks EventEmitter was working. I then reduced our project down to the bare minimum, but still could not get the greenworks events to fire. After trial and error, I discovered something odd: For the EventEmitter events to fire, you first need to call a random function from the api (any function, it seems) e.g. greenworks.getNumberOfPlayers(). The events will not fire unless you call something first (I'm calling initAPI() in all cases of course).

An easy way to reproduce is to comment out these lines in the electron sample main.js, and observe that the events are then not emitted.:

       greenworks.saveTextToFile('test_file.txt', 'test_content',
      function() { log('Save text to file successfully'); },
      function(err) { log('Failed on saving text to file'); });

       greenworks.readTextFromFile('test_file.txt', function(message) {
      log('Read text from file successfully.'); }, function(err) {
      log('Failed on reading text from file'); });

       greenworks.getCloudQuota(
      function() { log('Getting cloud quota successfully.') },
      function(err) { log('Failed on getting cloud quota.') });

       greenworks.activateAchievement('achievement',
      function() { log('Activating achievement successfully'); },
      function(err) { log('Failed on activating achievement.'); });

       greenworks.getNumberOfPlayers(
      function(a) { log("Number of players " + a) },
      function(err) { log ('Failed on getting number of players'); });

**Comment by hokein** [comment]
@bgSosh Hmm, it's weird.  The implementation works fine on nw.js v0.12.1 and node v4. 

After some more investigation, I find out the reason: the `uv_loop` in electron doesn't get activated, so the pull `SteamAPI_Runbacks()` method isn't invoked actually, which is a bug of electron(And electron works it through [a wrap function](https://github.com/atom/electron/blob/master/atom/common/lib/init.coffee#L21-L27)).

So I think the current workaround is to call `process.activateUvLoop()` before `greenworks.initAPI()`.

**Comment by bgSosh** [comment]
@hokein Ah, good you found it!  I'll make a note of the workaround.  Currently as a workaround we are calling getCloudQuota() straight after initAPI(), and it then seems to behave as expected.

Do you think there's enough information to submit a bug report to electron?  (I'm wondering if something similar might be causing the overlay problems in the later electron versions - probably not related though)

**Comment by hokein** [comment]
> Do you think there's enough information to submit a bug report to electron? (I'm wondering if something similar might be causing the overlay problems in the later electron versions - probably not related though)

No need. After discussing with the creator of `electron`, this is a limitation of how electron handles the node event loop. The electron only listens the backend fd and some events do not activate the backend fd.

**Comment by bgSosh** [comment]
It turns out that this workaround solved another issue we were having when trying to secure node-access with remote scripts in electron.  Greenworks functions didn't seem to be working properly when called in the preload script, but with this it's working.  Thanks!

**Comment by hokein** [comment]
I believe it's also a reason why your original `OnMicroTxnAuthorizationResponse` code doesn't work.
I'm closing this as it has been solved.

**Comment by aftokinito** [comment]
This seems to still be an issue:
`process.activateUvLoop();
greenworks.init();
greenworks.on("persona-state-changed", (resSteamID, personaChangeFlag) => {
	console.log("Test"); // this is never called
})
let res = greenworks.requestUserInformation(steamID, true);
// res is undefined here`

I've looked around and found this:
`greenworks._steam_events.on = function () {
  greenworks.emit.apply(greenworks, arguments);
};`

greenworks.emit.apply is called a bunch of times when greenworks.init() is called and then it's never called again.
