### ISSUE TITLE
Greenworks module cannot be found, but file is in the correct location

### ISSUE THREAD

**Issue by twinmatrix** [greenheartgames/greenworks#62]
Copy & paste from a closed topic (I didn't realize it was closed when I posted, sorry):

https://github.com/greenheartgames/greenworks/issues/26

I have the same problem. I'm using RPG Maker MV's internal NW build that creates a Game.exe. I copied ALL Steam SDK files and renamed Game.exe into nw.exe but it doesn't help.

![image](https://cloud.githubusercontent.com/assets/15997983/11365394/65edc8dc-92a6-11e5-971d-1a248f39ace0.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365398/6c803e78-92a6-11e5-9b47-61ad58b25105.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365399/7137ec22-92a6-11e5-88cd-9ae9ba5735f9.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365402/774cb836-92a6-11e5-8f01-edc7fdc910f2.png)
![image](https://cloud.githubusercontent.com/assets/15997983/11365403/7dd60d74-92a6-11e5-9541-62a2d58fbd8e.png)

**Comment by twinmatrix** [comment]
PS: Do I need to donate for support or does that come after receiving it? :)

**Comment by patrickklug** [comment]
Greenworks is built for a very specific version of nw.exe - As a first step, I'd confirm which version gamemaker uses and then check if you are using the correct greenworks release.

Greenworks is an open source project and generally we don't offer paid support. Donations are of course welcome but go towards further feature development.

**Comment by patrickklug** [comment]
The exe file also needs to be called nw.exe, otherwise this will not work but I think you might also have a version mismatch.

**Comment by twinmatrix** [comment]
Hey Patrick!

Thank you very much for the reply. I did rename Game.exe to nw.exe but after I took the screenshots.

I just retrieved version info. I believe it's 0.12.13? But I can't find a Greenworks release for this?

![image](https://cloud.githubusercontent.com/assets/15997983/11383385/08461d62-9308-11e5-896b-d03dd7fa0caa.png)

**Comment by patrickklug** [comment]
yea, the last version we have a release for is 0.12.1

We have to manually build those, so it's not practical to build a release for every minor version.

You might be able to just exchange the node-webkit version in your release to a supported one. Alternatively, you could also build greenworks yourself.

**Comment by twinmatrix** [comment]
Awesome, simply replacing the nw files with 0.12.1 fixed it! Thank you for the help. :)

**Comment by patrickklug** [comment]
great to hear. Good luck with it and don't forget to add your project here, once it's available on steam:

https://github.com/greenheartgames/greenworks/wiki/Apps-games-using-greenworks

**Comment by twinmatrix** [comment]
If I could sneak one more question in... I seem to have trouble getting the actual achievement call to work.

![image](https://cloud.githubusercontent.com/assets/15997983/11384096/327fcfec-930d-11e5-8a1c-a420174781e3.png)

![image](https://cloud.githubusercontent.com/assets/15997983/11384094/27b41f28-930d-11e5-9f6f-d67a068c7ea7.png)

![image](https://cloud.githubusercontent.com/assets/15997983/11384101/3cda17e0-930d-11e5-9584-fea7ab4d8d02.png)

**Comment by twinmatrix** [comment]
Eek, just too late for closing. Haha.

I will! ^_^ We're releasing next month.
