### ISSUE TITLE
Support for NW.js 0.13+

### ISSUE THREAD

**Issue by AshleyScirra** [greenheartgames/greenworks#64]
NW.js 0.13.0 is now in beta (beta2 is out). I can't seem to get the latest Greenworks to work with it. The require("./greenworks") line throws "Uncaught Error: The specified procedure could not be found.
\\?\C:\Users\Ashley\AppData\Local\Temp\nw9220_5633\greenworks-win32.node". (I've checked, the file given in that path does exist, but it sounds like it can't find a method within it.)

Could Greenworks be updated for 0.13 support?

**Comment by MadSpyxFR** [comment]
Greenworks depends of NAN, I guess as soon as NAN is updated for NW13/Node v5.x, an update will be available.

**Comment by hokein** [comment]
Sounds reasonable to provide a version for NW.js v0.13.0 now. 

The NAN v2.1.0 is working fine with Node v5 now. @AshleyScirra you may try to build a custom version of `greenworks` for NW.js v0.13.0.

**Comment by condolent** [comment]
Any update on this? Anyone heard of a greenworks update for 0.13?

**Comment by konistehrad** [comment]
So far the problem I'm having here is: `nw-gyp` doesn't support MSVS 2015, but MSVS 2015 is required to build against modern V8. Anything we could do to kick back to `node-gyp` proper to build against nwjs would be ideal right now.

**Comment by AshleyScirra** [comment]
I tried building it myself with NWjs 0.13.0-beta5 support, and I just get a huge pile of C++ template errors in v8.h. I've no idea why (but I'm not surprised, this is pretty much my typical experience trying to build anyone else's code). Can someone who already has a dev environment just hit build and publish a new release?

**Comment by AshleyScirra** [comment]
OK, after wrestling with nw-gyp configure and hacking a random .py file to know what MSVS 2015 and 2015e are, it works! However I don't have the setup to compile for Mac or Linux right now. Since it seems to be compatible simply doing an up-to-date rebuild, surely an official release is warranted to cover 0.13+ support?

**Comment by konistehrad** [comment]
@AshleyScirra for me, that was caused by trying to build against an old version of MSVS. That said, even when I built it, it would error out and crash on startup, making my build pretty useless. Have you tried to start your application with this build yet?

**Comment by MadSpyxFR** [comment]
Congrats @AshleyScirra , for Mac and Linux I use a VM for each one.

**Comment by condolent** [comment]
@AshleyScirra sweet! Will you update the C2 greenworks plugin now when it works, finally? :)

**Comment by morgondag** [comment]
@AshleyScirra great news!

**Comment by hokein** [comment]
There is still a issue on nw.js v0.13.0. I ran Greenworks on nw.js v0.13.0-beta5 on OS X, but nw.js crashed:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v87Isolate10GetCurrentEv
```
Seems it's a known issue, which is reported in https://groups.google.com/forum/#!msg/nwjs-general/T7ZHQVny0sE/bKO3Bt3XAQAJ. We need to wait for upstream to fix this problem before supporting nw.js v0.13.

**Comment by hokein** [comment]
nw.js v0.13.0-beta6 is released. From the change log:

> NW.js is able to support native modules built by node-gyp/npm now. 'nw-gyp' is not needed any more. See more information here:https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ

the native modules are supported now.

**Comment by AshleyScirra** [comment]
@hokein - I'm not quite clear on what the impact of this is - does it mean we can use existing releases with NW.js 0.13 beta6+, or is it just something that makes it easier to build Greenworks?

**Comment by hokein** [comment]
@AshleyScirra 
You cannot use the existing releases binary of Greenworks with NW.js 0.13.0 beta 6+. That means it's easy to build Greenworks (Just use `node-gyp`, `nw-gyp` is no longer needed). 

Steps of building Greenworks with NW.js 0.13.0 beta 7:

```
// install node.js v5.6.0
nvm install v5.6.0
nvm use v5.6.0

npm install -g node-gyp

cd path/to/Greenworks
node-gyp rebuild
```

**Comment by hokein** [comment]
A new release of Greenworks v0.5.2 for NW.js v0.13.0-beta7 has been published now.

**Comment by AshleyScirra** [comment]
@hokein - that's great, thanks! However it looks like it's missing the linux32 and win32 builds, it's only got 64-bit builds. Would it be easy to build them too? I did not yet get round to setting up the VMs we need to run these builds.

**Comment by hokein** [comment]
@AshleyScirra 
Oh, I miss the 32 bits version from reading the nw.js v0.13 [announcement](http://nwjs.io/blog/v0.13.0-beta7/). Have add the 32 bits binary now.

**Comment by konistehrad** [comment]
@hokein you're the best was about to ask. Thanks again for being on the ball!! :+1:

**Comment by AshleyScirra** [comment]
@hokein - unfortunately the updated download causes NWjs to crash on startup now, on both the win32 and win64 versions (where previously win64 worked). Did you change anything about the build?

**Comment by MadSpyxFR** [comment]
@AshleyScirra my build of greenworks works as intended with C2 as my own plugin (C2-221/NW13b7)

**Comment by hokein** [comment]
@AshleyScirra 
Hmm, I didn't change anything about the build. I run the sample of nw.js, it works on both 32 bits and 64 bits Windows 7.

**Comment by AshleyScirra** [comment]
@hokein - so I tried again today, double checked everything, and it's still not working... even the 64-bit version which previously worked does not work with the updated build. Are you sure you didn't update the Steamworks SDK or something? I'm using 1.36. Here's my test app (win64 version) which is using NW.js 0.13.0-beta7 and the latest Greenworks build: https://dl.dropboxusercontent.com/u/15217362/greenworks013.zip - just crashes on startup here, I checked and it's the require("./greenworks") line that crashes. Maybe I missed something obvious but I'm pretty sure this was working before the update!

**Comment by hokein** [comment]
@AshleyScirra 
OK, I will try to take a look on your case.

Could you try to run the [sample](https://github.com/greenheartgames/greenworks/tree/master/samples/nw.js) of nw.js in greenworks repo on Windows?

**Comment by hokein** [comment]
@AshleyScirra 
A crash log (not appear every time):
```
 GetHandleVerifier [0x000007FEE2AA9071+220849]
        v8::Extension::~Extension [0x000007FEE2A585FC+832220]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE48AAE93+1482547]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE48AFDF1+1502865]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE48A73B8+1467480]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE48AF7B6+1501270]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE487CE09+1293993]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32F2EDD+132877]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32ECE67+108183]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32EC7C5+106485]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32F4611+138817]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32F4E28+140888]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32F5388+142264]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32F44C5+138485]
        v8::ResourceConstraints::set_code_range_size [0x000007FEE32F13E2+125970]
        GetHandleVerifier [0x000007FEE2AB3726+263526]
        GetHandleVerifier [0x000007FEE2AB2D11+260945]
        GetHandleVerifier [0x000007FEE2AB341B+262747]
        GetHandleVerifier [0x000007FEE2A9BDE8+166952]
        v8::Extension::~Extension [0x000007FEE2A62D20+875008]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE4849D3E+1084894]
        std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptF                         rame> >::_Reallocate [0x000007FEE484A69F+1087295]
        GetHandleVerifier [0x000007FEE2A7FD96+52182]
        GetHandleVerifier [0x000007FEE2A8F437+115319]
        BaseThreadInitThunk [0x000000007743652D+13]
        RtlUserThreadStart [0x000000007756C521+33]
```

I also find a weird thing: if you type `var a = require(./greenworks`)` in devtools, it will work.

**Comment by AshleyScirra** [comment]
With NW.js 0.13.0-rc1, it's slightly different: it doesn't crash, but it reports it can't find the module, e.g.:

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Ashley\Desktop\nw\win32\greenworks-win32.node

However if I browse to that path, the file definitely exists there! This is pretty strange...

**Comment by hokein** [comment]
@AshleyScirra 
Are you building greenworks for nw.js v0.13.0-rc1?

The release of greenworks should not work with rc1 because the release binaries are built in node v5.6.0 while nw.js v0.13.0-rc1 has updated to node v5.7.0.
