### ISSUE TITLE
Info API example and additional questions

### ISSUE THREAD

**Issue by Aheri** [greenheartgames/greenworks#65]
This is not really an issue. 
Can you put example of usage greenworks.getSteamId() into samples?

Im beginner in JS/Node. I was working only with HTML and PHP.
From what I understand - I can create multiplayer game (I will be able to invite people from steam to game and they will be able to join game in any moment) with Greenworks, yes? 
// From "games using greenworks" only Might & Magic Heroes Online looks like true multiplayer game.
// im planning to use Socket.io as server in my APP
I just want to be sure of that before I fall into learning JS.

**Comment by hokein** [comment]
The `greenworks.getSteamId()` APIs only retrieves the information of the current user. The usage is quite straightforward, just can call it directly.
