### ISSUE TITLE
Avast detecting greenworks-win32.node and blocking, causing black screen

### ISSUE THREAD

**Issue by Raicuparta** [greenheartgames/greenworks#66]
Several users have reported to me that in my game, the antivirus Avast detects greenworks as a threat and quarantines it.

**Comment by konistehrad** [comment]
Did you build the binary yourself, or use the prebuilt? Trying to figure out if this will be an issue in my upcoming game; your help is super appreciated.

**Comment by Raicuparta** [comment]
Prebuilt. A user told me greenworks-win32.node was the responsible file, but I wasn't able to get any antivirus software to detect it myself.

**Comment by MarxGames** [comment]
Kaspersky does the same for our game, using a prebuilt binary http://puu.sh/nVHmL/ff64ea3f2f.png http://steamcommunity.com/app/372800/discussions/0/385429254936757410/

**Comment by patrickklug** [comment]
We have seen similar issues. So far, every time I investigated it, it turned out to be a false positive but I can't figure out what specifically causes the false detection.

**Comment by marwanhilmi** [comment]
We are getting a few reports from Avast as well - I compiled the libraries myself. Not 100% which file is responsible but I imagine it is the `*win32.node` files.

**Comment by hokein** [comment]
I'm closing it as we can do nothing from greenworks side.
