### ISSUE TITLE
ISteamFriends.h

### ISSUE THREAD

**Issue by fletchette** [greenheartgames/greenworks#67]
Are there any plans to add in the stuff from ISteamFriends?

**Comment by hokein** [comment]
Which features in `ISteamFriends` do you want?

**Comment by fletchette** [comment]
Knew I was forgetting something.

GetPersonaName()
GetPersonaState()
GetFriendCount()
GetFriendByIndex()
GetFriendPersonaName()
GetFriendSteamLevel()
GetPlayerNickname()

GetSmallFriendAvatar()
GetMediumFriendAvatar()
GetLargeFriendAvatar()

SetListenForFriendsMessages()
ReplyToFriendMessage()
GetFriendMessage()

Would any of those be possible?

**Comment by marwanhilmi** [comment]
@fletchette This is partially implemented here https://github.com/greenheartgames/greenworks/pull/82

**Comment by hokein** [comment]
Closing it as it is implemented in #82, #85.

**Comment by fletchette** [comment]
@hokein 
A *lot* of the stuff I listed has not been implemented.

**Comment by hokein** [comment]
@fletchette The missing parts are implemented now.
