### ISSUE TITLE
nw-gyp failing to download tarball

### ISSUE THREAD

**Issue by jonmulcahy** [greenheartgames/greenworks#70]
I ran the nw-gyp configure command and it failed. It's trying to download a tar.gz file from amazonaws, but that file does not exist anymore. thoughts?

C:\Dropbox\scratch\Steam>nw-gyp configure
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@5.7.0 | win32 | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v5.7.0/nw-headers-v5.7.0.tar.gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v5.7.0/nw-headers-v5.7.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (C:\Users\i64329\AppData\Roaming\npm\node_modules\nw-gyp\lib\install.js:236:14)
gyp ERR! stack     at emitOne (events.js:95:20)
gyp ERR! stack     at Request.emit (events.js:182:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\i64329\AppData\Roaming\npm\node_modules\nw-gyp\node_modules\request\request.js:962:10)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at ClientRequest.emit (events.js:182:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:458:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:348:20)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i64329\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "configure"
gyp ERR! cwd C:\Dropbox\scratch\Steam
gyp ERR! node -v v5.7.0
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok

**Comment by hokein** [comment]
`nw-gyp` isn't needed any more in nw v0.13.0, just use `node-gyp`. For more details, please refer to https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ.
