### ISSUE TITLE
Encrypted tickets decrypting support

### ISSUE THREAD

**Issue by artch** [greenheartgames/greenworks#93]
We're working on nodejs-based server for an online game, and now looking into possible solutions for creating Steam integration. We'd like to make use of Encrypted Application Tickets to avoid connecting to Steam servers each time a user tries to authenticate with his SteamID. As far as I can tell the following APIs are missing in greenworks:

`SteamEncryptedAppTicket_BDecryptTicket`
`SteamEncryptedAppTicket_BIsTicketForApp()`
`SteamEncryptedAppTicket_GetTicketIssueTime()`
`SteamEncryptedAppTicket_GetTicketSteamID`

Any chance they will be added soon?

**Comment by hokein** [comment]
It is reasonable to add these APIs in greenworks.

**Comment by artch** [comment]
Nice! What is a possible ETA for it then?

**Comment by hokein** [comment]
@artch I can't guarantee the exact time (Maybe wait for the next release for nw.js/electron upgrade to chrome 54), but I will take a look in the following weeks. 

By the way, are you willing to help to test the APIs if I implement them in greenworks? I'm not sure I have such server environments.

**Comment by artch** [comment]
Yes, I can help with testing, but I'm not sure I have all the requirements to set up the environment for building greenworks from sources, so I'd need some prebuilt binaries for testing.

**Comment by hokein** [comment]
@arch Great, thanks. 
What's your use case? From your above words, you are likely to use Greenworks in a nodejs app? If so, it won't be too troublesome to build the greenworks source (Just download steamsdk, clone the greenworks sourcecode, and build it).

**Comment by artch** [comment]
OK, I managed to build greenworks succesfully on Windows 10 x64 and Ubuntu 16.04 LTS. Looking forward to test the encrypted ticket APIs.

By the way, I'd like to mention that once this feature is implemented, we're going to donate $100 to greenworks as a little encouragement. Keep up the good work! :)

**Comment by hokein** [comment]
@artch Maybe you could use https://www.bountysource.com/ to post a bounty for this issue.

**Comment by artch** [comment]
https://www.bountysource.com/issues/38293423-encrypted-tickets-decrypting-support

**Comment by artch** [comment]
This feature is broken on Linux - see #97.
