### ISSUE TITLE
Missing module when it is there

### ISSUE THREAD

**Issue by fletchette** [greenheartgames/greenworks#96]
In nw.js I keep getting this error - 
http://i.imgur.com/z6z7rsX.png

Even though the .node file is where its supposed to be
http://i.imgur.com/bMsq0J2.png

**Comment by hokein** [comment]
Looks like you are using nw-biolerplate, I don't known much about it. Doest it build a `.nw` app? Your issue might be related to #26.

**Comment by fletchette** [comment]
Tested again with a clean install with no generator -
http://i.imgur.com/V9hqtrg.png
http://i.imgur.com/RfpapCS.png
http://i.imgur.com/ADaF2nP.png

Same thing happens when running straight from a folder or from a .nw

**Comment by MadSpyxFR** [comment]
Could you try to add the steam_api64.dll and steam_api.lib and steam_api64.lib in your "lib" folder ?

**Comment by fletchette** [comment]
@MadSpyxFR 
Tried your suggestion and it fixed it.
Thanks!
