### ISSUE TITLE
Absolute path to encryptedappticket library hardcoded on compiling

### ISSUE THREAD

**Issue by artch** [greenheartgames/greenworks#97]
Environment: Ubuntu linux 15.10 x64

When I rebuild greenworks with the encryptedappticket library support, it gets hardcoded into the `greenworks.node` with an absolute path, producing such an error when trying to include it on another machine:

```
require('./greenworks-linux64')

Error: /mnt/ext/greenworks/deps/steamworks_sdk/public/steam/lib/linux64/libsdkencryptedappticket.so: cannot open shared object file: No such file or directory
```

When I open the greenworks.node file in a binary editor, I can see that the absolute path is saved there, rather than a relative path `libsdkencryptedappticket.so`.

**Comment by hokein** [comment]
@artch Thanks for report. It should be fixed now.
